/*
    This file is part of the WebKit open source project.
    This file has been generated by generate-bindings.pl. DO NOT MODIFY!

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Library General Public
    License as published by the Free Software Foundation; either
    version 2 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Library General Public License for more details.

    You should have received a copy of the GNU Library General Public License
    along with this library; see the file COPYING.LIB.  If not, write to
    the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
    Boston, MA 02111-1307, USA.
*/

#include "config.h"
#include "V8ArrayBuffer.h"

#if ENABLE(3D_CANVAS)

#include "RuntimeEnabledFeatures.h"
#include "V8Binding.h"
#include "V8BindingState.h"
#include "V8DOMWrapper.h"
#include "V8IsolatedContext.h"
#include "V8Proxy.h"

namespace WebCore {

WrapperTypeInfo V8ArrayBuffer::info = { V8ArrayBuffer::GetTemplate, V8ArrayBuffer::derefObject, 0 };

namespace ArrayBufferInternal {

template <typename T> void V8_USE(T) { }

static v8::Handle<v8::Value> byteLengthAttrGetter(v8::Local<v8::String> name, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.ArrayBuffer.byteLength._get");
    ArrayBuffer* imp = V8ArrayBuffer::toNative(info.Holder());
    return v8::Integer::New(imp->byteLength());
}

} // namespace ArrayBufferInternal

static const BatchedAttribute ArrayBufferAttrs[] = {
    // Attribute 'byteLength' (Type: 'readonly attribute' ExtAttr: '')
    {"byteLength", ArrayBufferInternal::byteLengthAttrGetter, 0, 0 /* no data */, static_cast<v8::AccessControl>(v8::DEFAULT), static_cast<v8::PropertyAttribute>(v8::None), 0 /* on instance */},
};
static v8::Persistent<v8::FunctionTemplate> ConfigureV8ArrayBufferTemplate(v8::Persistent<v8::FunctionTemplate> desc)
{
    v8::Local<v8::Signature> defaultSignature = configureTemplate(desc, "ArrayBuffer", v8::Persistent<v8::FunctionTemplate>(), V8ArrayBuffer::internalFieldCount,
        ArrayBufferAttrs, sizeof(ArrayBufferAttrs) / sizeof(*ArrayBufferAttrs),
        0, 0);
        desc->SetCallHandler(V8ArrayBuffer::constructorCallback);
    

    // Custom toString template
    desc->Set(getToStringName(), getToStringTemplate());
    return desc;
}

v8::Persistent<v8::FunctionTemplate> V8ArrayBuffer::GetRawTemplate()
{
    static v8::Persistent<v8::FunctionTemplate> V8ArrayBufferRawCache = createRawTemplate();
    return V8ArrayBufferRawCache;
}

v8::Persistent<v8::FunctionTemplate> V8ArrayBuffer::GetTemplate()
{
    static v8::Persistent<v8::FunctionTemplate> V8ArrayBufferCache = ConfigureV8ArrayBufferTemplate(GetRawTemplate());
    return V8ArrayBufferCache;
}

ArrayBuffer* V8ArrayBuffer::toNative(v8::Handle<v8::Object> object)
{
    return reinterpret_cast<ArrayBuffer*>(object->GetPointerFromInternalField(v8DOMWrapperObjectIndex));
}

bool V8ArrayBuffer::HasInstance(v8::Handle<v8::Value> value)
{
    return GetRawTemplate()->HasInstance(value);
}


v8::Handle<v8::Object> V8ArrayBuffer::wrap(ArrayBuffer* impl)
{
    v8::Handle<v8::Object> wrapper;
    V8Proxy* proxy = 0;
        wrapper = getDOMObjectMap().get(impl);
        if (!wrapper.IsEmpty())
            return wrapper;
    wrapper = V8DOMWrapper::instantiateV8Object(proxy, &info, impl);
    if (wrapper.IsEmpty())
        return wrapper;

    impl->ref();
    getDOMObjectMap().set(impl, v8::Persistent<v8::Object>::New(wrapper));
    return wrapper;
}

v8::Handle<v8::Value> toV8(PassRefPtr<ArrayBuffer > impl)
{
    return toV8(impl.get());
}

v8::Handle<v8::Value> toV8(ArrayBuffer* impl)
{
    if (!impl)
        return v8::Null();
    return V8ArrayBuffer::wrap(impl);
}

void V8ArrayBuffer::derefObject(void* object)
{
    static_cast<ArrayBuffer*>(object)->deref();
}

} // namespace WebCore

#endif // ENABLE(3D_CANVAS)
