/*
    This file is part of the WebKit open source project.
    This file has been generated by generate-bindings.pl. DO NOT MODIFY!

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Library General Public
    License as published by the Free Software Foundation; either
    version 2 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Library General Public License for more details.

    You should have received a copy of the GNU Library General Public License
    along with this library; see the file COPYING.LIB.  If not, write to
    the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
    Boston, MA 02111-1307, USA.
*/

#include "config.h"
#include "V8Blob.h"

#include "ExceptionCode.h"
#include "RuntimeEnabledFeatures.h"
#include "V8Binding.h"
#include "V8BindingMacros.h"
#include "V8BindingState.h"
#include "V8DOMWrapper.h"
#include "V8IsolatedContext.h"
#include "V8Proxy.h"
#include <wtf/GetPtr.h>
#include <wtf/RefCounted.h>
#include <wtf/RefPtr.h>

namespace WebCore {

WrapperTypeInfo V8Blob::info = { V8Blob::GetTemplate, V8Blob::derefObject, 0 };

namespace BlobInternal {

template <typename T> void V8_USE(T) { }

static v8::Handle<v8::Value> sizeAttrGetter(v8::Local<v8::String> name, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.Blob.size._get");
    Blob* imp = V8Blob::toNative(info.Holder());
    return v8::Number::New(static_cast<double>(imp->size()));
}

static v8::Handle<v8::Value> typeAttrGetter(v8::Local<v8::String> name, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.Blob.type._get");
    Blob* imp = V8Blob::toNative(info.Holder());
    return v8String(imp->type());
}

static v8::Handle<v8::Value> sliceCallback(const v8::Arguments& args)
{
    INC_STATS("DOM.Blob.slice");
    Blob* imp = V8Blob::toNative(args.Holder());
    EXCEPTION_BLOCK(long long, start, toInt64(args[0]));
    EXCEPTION_BLOCK(long long, length, toInt64(args[1]));
    if (args.Length() <= 2) {
        ScriptExecutionContext* scriptContext = getScriptExecutionContext();
        if (!scriptContext)
            return v8::Undefined();
        return toV8(imp->slice(scriptContext, start, length));
    }
    STRING_TO_V8PARAMETER_EXCEPTION_BLOCK(V8Parameter<WithUndefinedOrNullCheck>, contentType, args[2]);
    ScriptExecutionContext* scriptContext = getScriptExecutionContext();
    if (!scriptContext)
        return v8::Undefined();
    return toV8(imp->slice(scriptContext, start, length, contentType));
}

} // namespace BlobInternal

static const BatchedAttribute BlobAttrs[] = {
    // Attribute 'size' (Type: 'readonly attribute' ExtAttr: '')
    {"size", BlobInternal::sizeAttrGetter, 0, 0 /* no data */, static_cast<v8::AccessControl>(v8::DEFAULT), static_cast<v8::PropertyAttribute>(v8::None), 0 /* on instance */},
    // Attribute 'type' (Type: 'readonly attribute' ExtAttr: '')
    {"type", BlobInternal::typeAttrGetter, 0, 0 /* no data */, static_cast<v8::AccessControl>(v8::DEFAULT), static_cast<v8::PropertyAttribute>(v8::None), 0 /* on instance */},
};
static const BatchedCallback BlobCallbacks[] = {
    {"slice", BlobInternal::sliceCallback},
};
static v8::Persistent<v8::FunctionTemplate> ConfigureV8BlobTemplate(v8::Persistent<v8::FunctionTemplate> desc)
{
    v8::Local<v8::Signature> defaultSignature = configureTemplate(desc, "Blob", v8::Persistent<v8::FunctionTemplate>(), V8Blob::internalFieldCount,
        BlobAttrs, sizeof(BlobAttrs) / sizeof(*BlobAttrs),
        BlobCallbacks, sizeof(BlobCallbacks) / sizeof(*BlobCallbacks));
    v8::Local<v8::ObjectTemplate> instance = desc->InstanceTemplate();
    v8::Local<v8::ObjectTemplate> proto = desc->PrototypeTemplate();
    

    // Custom toString template
    desc->Set(getToStringName(), getToStringTemplate());
    return desc;
}

v8::Persistent<v8::FunctionTemplate> V8Blob::GetRawTemplate()
{
    static v8::Persistent<v8::FunctionTemplate> V8BlobRawCache = createRawTemplate();
    return V8BlobRawCache;
}

v8::Persistent<v8::FunctionTemplate> V8Blob::GetTemplate()
{
    static v8::Persistent<v8::FunctionTemplate> V8BlobCache = ConfigureV8BlobTemplate(GetRawTemplate());
    return V8BlobCache;
}

Blob* V8Blob::toNative(v8::Handle<v8::Object> object)
{
    return reinterpret_cast<Blob*>(object->GetPointerFromInternalField(v8DOMWrapperObjectIndex));
}

bool V8Blob::HasInstance(v8::Handle<v8::Value> value)
{
    return GetRawTemplate()->HasInstance(value);
}


v8::Handle<v8::Object> V8Blob::wrap(Blob* impl)
{
    v8::Handle<v8::Object> wrapper;
    V8Proxy* proxy = 0;
        wrapper = getDOMObjectMap().get(impl);
        if (!wrapper.IsEmpty())
            return wrapper;
    wrapper = V8DOMWrapper::instantiateV8Object(proxy, &info, impl);
    if (wrapper.IsEmpty())
        return wrapper;

    impl->ref();
    getDOMObjectMap().set(impl, v8::Persistent<v8::Object>::New(wrapper));
    return wrapper;
}

v8::Handle<v8::Value> toV8(PassRefPtr<Blob > impl)
{
    return toV8(impl.get());
}

v8::Handle<v8::Value> toV8(Blob* impl)
{
    if (!impl)
        return v8::Null();
    return V8Blob::wrap(impl);
}

void V8Blob::derefObject(void* object)
{
    static_cast<Blob*>(object)->deref();
}

} // namespace WebCore
