/*
    This file is part of the WebKit open source project.
    This file has been generated by generate-bindings.pl. DO NOT MODIFY!

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Library General Public
    License as published by the Free Software Foundation; either
    version 2 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Library General Public License for more details.

    You should have received a copy of the GNU Library General Public License
    along with this library; see the file COPYING.LIB.  If not, write to
    the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
    Boston, MA 02111-1307, USA.
*/

#include "config.h"
#include "V8CSSPageRule.h"

#include "CSSMutableStyleDeclaration.h"
#include "ExceptionCode.h"
#include "RuntimeEnabledFeatures.h"
#include "V8Binding.h"
#include "V8BindingState.h"
#include "V8CSSRule.h"
#include "V8CSSStyleDeclaration.h"
#include "V8DOMWrapper.h"
#include "V8IsolatedContext.h"
#include "V8Proxy.h"

namespace WebCore {

WrapperTypeInfo V8CSSPageRule::info = { V8CSSPageRule::GetTemplate, V8CSSPageRule::derefObject, 0 };

namespace CSSPageRuleInternal {

template <typename T> void V8_USE(T) { }

static v8::Handle<v8::Value> selectorTextAttrGetter(v8::Local<v8::String> name, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.CSSPageRule.selectorText._get");
    CSSPageRule* imp = V8CSSPageRule::toNative(info.Holder());
    return v8StringOrNull(imp->selectorText());
}

static void selectorTextAttrSetter(v8::Local<v8::String> name, v8::Local<v8::Value> value, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.CSSPageRule.selectorText._set");
    CSSPageRule* imp = V8CSSPageRule::toNative(info.Holder());
    V8Parameter<WithNullCheck> v = value;
    ExceptionCode ec = 0;
    imp->setSelectorText(v, ec);
    if (UNLIKELY(ec))
        V8Proxy::setDOMException(ec);
    return;
}

static v8::Handle<v8::Value> styleAttrGetter(v8::Local<v8::String> name, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.CSSPageRule.style._get");
    CSSPageRule* imp = V8CSSPageRule::toNative(info.Holder());
    RefPtr<CSSStyleDeclaration> result = imp->style();
    v8::Handle<v8::Value> wrapper = result.get() ? getDOMObjectMap().get(result.get()) : v8::Handle<v8::Value>();
    if (wrapper.IsEmpty()) {
        wrapper = toV8(result.get());
        if (!wrapper.IsEmpty())
            V8DOMWrapper::setHiddenReference(info.Holder(), wrapper);
    }
    return wrapper;
}

} // namespace CSSPageRuleInternal

static const BatchedAttribute CSSPageRuleAttrs[] = {
    // Attribute 'selectorText' (Type: 'attribute' ExtAttr: 'ConvertNullToNullString ConvertNullStringTo')
    {"selectorText", CSSPageRuleInternal::selectorTextAttrGetter, CSSPageRuleInternal::selectorTextAttrSetter, 0 /* no data */, static_cast<v8::AccessControl>(v8::DEFAULT), static_cast<v8::PropertyAttribute>(v8::None), 0 /* on instance */},
    // Attribute 'style' (Type: 'readonly attribute' ExtAttr: '')
    {"style", CSSPageRuleInternal::styleAttrGetter, 0, 0 /* no data */, static_cast<v8::AccessControl>(v8::DEFAULT), static_cast<v8::PropertyAttribute>(v8::None), 0 /* on instance */},
};
static v8::Persistent<v8::FunctionTemplate> ConfigureV8CSSPageRuleTemplate(v8::Persistent<v8::FunctionTemplate> desc)
{
    v8::Local<v8::Signature> defaultSignature = configureTemplate(desc, "CSSPageRule", V8CSSRule::GetTemplate(), V8CSSPageRule::internalFieldCount,
        CSSPageRuleAttrs, sizeof(CSSPageRuleAttrs) / sizeof(*CSSPageRuleAttrs),
        0, 0);
    

    // Custom toString template
    desc->Set(getToStringName(), getToStringTemplate());
    return desc;
}

v8::Persistent<v8::FunctionTemplate> V8CSSPageRule::GetRawTemplate()
{
    static v8::Persistent<v8::FunctionTemplate> V8CSSPageRuleRawCache = createRawTemplate();
    return V8CSSPageRuleRawCache;
}

v8::Persistent<v8::FunctionTemplate> V8CSSPageRule::GetTemplate()
{
    static v8::Persistent<v8::FunctionTemplate> V8CSSPageRuleCache = ConfigureV8CSSPageRuleTemplate(GetRawTemplate());
    return V8CSSPageRuleCache;
}

CSSPageRule* V8CSSPageRule::toNative(v8::Handle<v8::Object> object)
{
    return reinterpret_cast<CSSPageRule*>(object->GetPointerFromInternalField(v8DOMWrapperObjectIndex));
}

bool V8CSSPageRule::HasInstance(v8::Handle<v8::Value> value)
{
    return GetRawTemplate()->HasInstance(value);
}


v8::Handle<v8::Object> V8CSSPageRule::wrap(CSSPageRule* impl)
{
    v8::Handle<v8::Object> wrapper;
    V8Proxy* proxy = 0;
        wrapper = getDOMObjectMap().get(impl);
        if (!wrapper.IsEmpty())
            return wrapper;
    wrapper = V8DOMWrapper::instantiateV8Object(proxy, &info, impl);
    if (wrapper.IsEmpty())
        return wrapper;

    impl->ref();
    getDOMObjectMap().set(impl, v8::Persistent<v8::Object>::New(wrapper));
    return wrapper;
}

v8::Handle<v8::Value> toV8(PassRefPtr<CSSPageRule > impl)
{
    return toV8(impl.get());
}

v8::Handle<v8::Value> toV8(CSSPageRule* impl)
{
    if (!impl)
        return v8::Null();
    return V8CSSPageRule::wrap(impl);
}

void V8CSSPageRule::derefObject(void* object)
{
    static_cast<CSSPageRule*>(object)->deref();
}

} // namespace WebCore
