/*
    This file is part of the WebKit open source project.
    This file has been generated by generate-bindings.pl. DO NOT MODIFY!

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Library General Public
    License as published by the Free Software Foundation; either
    version 2 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Library General Public License for more details.

    You should have received a copy of the GNU Library General Public License
    along with this library; see the file COPYING.LIB.  If not, write to
    the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
    Boston, MA 02111-1307, USA.
*/

#include "config.h"
#include "V8DOMMimeType.h"

#include "RuntimeEnabledFeatures.h"
#include "V8Binding.h"
#include "V8BindingState.h"
#include "V8DOMPlugin.h"
#include "V8DOMWrapper.h"
#include "V8IsolatedContext.h"
#include "V8Proxy.h"

namespace WebCore {

WrapperTypeInfo V8DOMMimeType::info = { V8DOMMimeType::GetTemplate, V8DOMMimeType::derefObject, 0 };

namespace DOMMimeTypeInternal {

template <typename T> void V8_USE(T) { }

static v8::Handle<v8::Value> typeAttrGetter(v8::Local<v8::String> name, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.DOMMimeType.type._get");
    DOMMimeType* imp = V8DOMMimeType::toNative(info.Holder());
    return v8String(imp->type());
}

static v8::Handle<v8::Value> suffixesAttrGetter(v8::Local<v8::String> name, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.DOMMimeType.suffixes._get");
    DOMMimeType* imp = V8DOMMimeType::toNative(info.Holder());
    return v8String(imp->suffixes());
}

static v8::Handle<v8::Value> descriptionAttrGetter(v8::Local<v8::String> name, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.DOMMimeType.description._get");
    DOMMimeType* imp = V8DOMMimeType::toNative(info.Holder());
    return v8String(imp->description());
}

static v8::Handle<v8::Value> enabledPluginAttrGetter(v8::Local<v8::String> name, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.DOMMimeType.enabledPlugin._get");
    DOMMimeType* imp = V8DOMMimeType::toNative(info.Holder());
    RefPtr<DOMPlugin> result = imp->enabledPlugin();
    v8::Handle<v8::Value> wrapper = result.get() ? getDOMObjectMap().get(result.get()) : v8::Handle<v8::Value>();
    if (wrapper.IsEmpty()) {
        wrapper = toV8(result.get());
        if (!wrapper.IsEmpty())
            V8DOMWrapper::setHiddenReference(info.Holder(), wrapper);
    }
    return wrapper;
}

} // namespace DOMMimeTypeInternal

static const BatchedAttribute DOMMimeTypeAttrs[] = {
    // Attribute 'type' (Type: 'readonly attribute' ExtAttr: '')
    {"type", DOMMimeTypeInternal::typeAttrGetter, 0, 0 /* no data */, static_cast<v8::AccessControl>(v8::DEFAULT), static_cast<v8::PropertyAttribute>(v8::None), 0 /* on instance */},
    // Attribute 'suffixes' (Type: 'readonly attribute' ExtAttr: '')
    {"suffixes", DOMMimeTypeInternal::suffixesAttrGetter, 0, 0 /* no data */, static_cast<v8::AccessControl>(v8::DEFAULT), static_cast<v8::PropertyAttribute>(v8::None), 0 /* on instance */},
    // Attribute 'description' (Type: 'readonly attribute' ExtAttr: '')
    {"description", DOMMimeTypeInternal::descriptionAttrGetter, 0, 0 /* no data */, static_cast<v8::AccessControl>(v8::DEFAULT), static_cast<v8::PropertyAttribute>(v8::None), 0 /* on instance */},
    // Attribute 'enabledPlugin' (Type: 'readonly attribute' ExtAttr: '')
    {"enabledPlugin", DOMMimeTypeInternal::enabledPluginAttrGetter, 0, 0 /* no data */, static_cast<v8::AccessControl>(v8::DEFAULT), static_cast<v8::PropertyAttribute>(v8::None), 0 /* on instance */},
};
static v8::Persistent<v8::FunctionTemplate> ConfigureV8DOMMimeTypeTemplate(v8::Persistent<v8::FunctionTemplate> desc)
{
    v8::Local<v8::Signature> defaultSignature = configureTemplate(desc, "DOMMimeType", v8::Persistent<v8::FunctionTemplate>(), V8DOMMimeType::internalFieldCount,
        DOMMimeTypeAttrs, sizeof(DOMMimeTypeAttrs) / sizeof(*DOMMimeTypeAttrs),
        0, 0);
    

    // Custom toString template
    desc->Set(getToStringName(), getToStringTemplate());
    return desc;
}

v8::Persistent<v8::FunctionTemplate> V8DOMMimeType::GetRawTemplate()
{
    static v8::Persistent<v8::FunctionTemplate> V8DOMMimeTypeRawCache = createRawTemplate();
    return V8DOMMimeTypeRawCache;
}

v8::Persistent<v8::FunctionTemplate> V8DOMMimeType::GetTemplate()
{
    static v8::Persistent<v8::FunctionTemplate> V8DOMMimeTypeCache = ConfigureV8DOMMimeTypeTemplate(GetRawTemplate());
    return V8DOMMimeTypeCache;
}

DOMMimeType* V8DOMMimeType::toNative(v8::Handle<v8::Object> object)
{
    return reinterpret_cast<DOMMimeType*>(object->GetPointerFromInternalField(v8DOMWrapperObjectIndex));
}

bool V8DOMMimeType::HasInstance(v8::Handle<v8::Value> value)
{
    return GetRawTemplate()->HasInstance(value);
}


v8::Handle<v8::Object> V8DOMMimeType::wrap(DOMMimeType* impl)
{
    v8::Handle<v8::Object> wrapper;
    V8Proxy* proxy = 0;
        wrapper = getDOMObjectMap().get(impl);
        if (!wrapper.IsEmpty())
            return wrapper;
    wrapper = V8DOMWrapper::instantiateV8Object(proxy, &info, impl);
    if (wrapper.IsEmpty())
        return wrapper;

    impl->ref();
    getDOMObjectMap().set(impl, v8::Persistent<v8::Object>::New(wrapper));
    return wrapper;
}

v8::Handle<v8::Value> toV8(PassRefPtr<DOMMimeType > impl)
{
    return toV8(impl.get());
}

v8::Handle<v8::Value> toV8(DOMMimeType* impl)
{
    if (!impl)
        return v8::Null();
    return V8DOMMimeType::wrap(impl);
}

void V8DOMMimeType::derefObject(void* object)
{
    static_cast<DOMMimeType*>(object)->deref();
}

} // namespace WebCore
