/*
    This file is part of the WebKit open source project.
    This file has been generated by generate-bindings.pl. DO NOT MODIFY!

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Library General Public
    License as published by the Free Software Foundation; either
    version 2 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Library General Public License for more details.

    You should have received a copy of the GNU Library General Public License
    along with this library; see the file COPYING.LIB.  If not, write to
    the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
    Boston, MA 02111-1307, USA.
*/

#include "config.h"
#include "V8HTMLCanvasElement.h"

#include "RuntimeEnabledFeatures.h"
#include "V8Binding.h"
#include "V8BindingState.h"
#include "V8DOMWrapper.h"
#include "V8HTMLElement.h"
#include "V8IsolatedContext.h"
#include "V8Proxy.h"

namespace WebCore {

WrapperTypeInfo V8HTMLCanvasElement::info = { V8HTMLCanvasElement::GetTemplate, V8HTMLCanvasElement::derefObject, 0 };

namespace HTMLCanvasElementInternal {

template <typename T> void V8_USE(T) { }

static v8::Handle<v8::Value> widthAttrGetter(v8::Local<v8::String> name, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.HTMLCanvasElement.width._get");
    HTMLCanvasElement* imp = V8HTMLCanvasElement::toNative(info.Holder());
	if (!R_check(imp)) return v8::Handle<v8::Value>(v8::Undefined());
    return v8::Integer::New(imp->width());
}

static void widthAttrSetter(v8::Local<v8::String> name, v8::Local<v8::Value> value, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.HTMLCanvasElement.width._set");
    HTMLCanvasElement* imp = V8HTMLCanvasElement::toNative(info.Holder());
    int v = toInt32(value);
    imp->setWidth(v);
    return;
}

static v8::Handle<v8::Value> heightAttrGetter(v8::Local<v8::String> name, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.HTMLCanvasElement.height._get");
    HTMLCanvasElement* imp = V8HTMLCanvasElement::toNative(info.Holder());
	if (!R_check(imp)) return v8::Handle<v8::Value>(v8::Undefined());
    return v8::Integer::New(imp->height());
}

static void heightAttrSetter(v8::Local<v8::String> name, v8::Local<v8::Value> value, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.HTMLCanvasElement.height._set");
    HTMLCanvasElement* imp = V8HTMLCanvasElement::toNative(info.Holder());
    int v = toInt32(value);
    imp->setHeight(v);
    return;
}

} // namespace HTMLCanvasElementInternal

static const BatchedAttribute HTMLCanvasElementAttrs[] = {
    // Attribute 'width' (Type: 'attribute' ExtAttr: '')
    {"width", HTMLCanvasElementInternal::widthAttrGetter, HTMLCanvasElementInternal::widthAttrSetter, 0 /* no data */, static_cast<v8::AccessControl>(v8::DEFAULT), static_cast<v8::PropertyAttribute>(v8::None), 0 /* on instance */},
    // Attribute 'height' (Type: 'attribute' ExtAttr: '')
    {"height", HTMLCanvasElementInternal::heightAttrGetter, HTMLCanvasElementInternal::heightAttrSetter, 0 /* no data */, static_cast<v8::AccessControl>(v8::DEFAULT), static_cast<v8::PropertyAttribute>(v8::None), 0 /* on instance */},
};
static const BatchedCallback HTMLCanvasElementCallbacks[] = {
    {"toDataURL", V8HTMLCanvasElement::toDataURLCallback},
    {"getContext", V8HTMLCanvasElement::getContextCallback},
};
static v8::Persistent<v8::FunctionTemplate> ConfigureV8HTMLCanvasElementTemplate(v8::Persistent<v8::FunctionTemplate> desc)
{
    v8::Local<v8::Signature> defaultSignature = configureTemplate(desc, "HTMLCanvasElement", V8HTMLElement::GetTemplate(), V8HTMLCanvasElement::internalFieldCount,
        HTMLCanvasElementAttrs, sizeof(HTMLCanvasElementAttrs) / sizeof(*HTMLCanvasElementAttrs),
        HTMLCanvasElementCallbacks, sizeof(HTMLCanvasElementCallbacks) / sizeof(*HTMLCanvasElementCallbacks));
    v8::Local<v8::ObjectTemplate> instance = desc->InstanceTemplate();
    v8::Local<v8::ObjectTemplate> proto = desc->PrototypeTemplate();
    

    // Custom toString template
    desc->Set(getToStringName(), getToStringTemplate());
    return desc;
}

v8::Persistent<v8::FunctionTemplate> V8HTMLCanvasElement::GetRawTemplate()
{
    static v8::Persistent<v8::FunctionTemplate> V8HTMLCanvasElementRawCache = createRawTemplate();
    return V8HTMLCanvasElementRawCache;
}

v8::Persistent<v8::FunctionTemplate> V8HTMLCanvasElement::GetTemplate()
{
    static v8::Persistent<v8::FunctionTemplate> V8HTMLCanvasElementCache = ConfigureV8HTMLCanvasElementTemplate(GetRawTemplate());
    return V8HTMLCanvasElementCache;
}

HTMLCanvasElement* V8HTMLCanvasElement::toNative(v8::Handle<v8::Object> object)
{
    return reinterpret_cast<HTMLCanvasElement*>(object->GetPointerFromInternalField(v8DOMWrapperObjectIndex));
}

bool V8HTMLCanvasElement::HasInstance(v8::Handle<v8::Value> value)
{
    return GetRawTemplate()->HasInstance(value);
}


v8::Handle<v8::Object> V8HTMLCanvasElement::wrap(HTMLCanvasElement* impl, bool forceNewObject)
{
    v8::Handle<v8::Object> wrapper;
    V8Proxy* proxy = 0;
    if (impl->document()) {
        proxy = V8Proxy::retrieve(impl->document()->frame());
        if (proxy && static_cast<Node*>(impl->document()) == static_cast<Node*>(impl))
            proxy->windowShell()->initContextIfNeeded();
    }

    if (!forceNewObject) {
        wrapper = V8DOMWrapper::getWrapper(impl);
        if (!wrapper.IsEmpty())
            return wrapper;
    }

    v8::Handle<v8::Context> context;
    if (proxy)
        context = proxy->context();

    // Enter the node's context and create the wrapper in that context.
    if (!context.IsEmpty())
        context->Enter();
    wrapper = V8DOMWrapper::instantiateV8Object(proxy, &info, impl);
    // Exit the node's context if it was entered.
    if (!context.IsEmpty())
        context->Exit();
    if (wrapper.IsEmpty())
        return wrapper;

    impl->ref();
    getDOMNodeMap().set(impl, v8::Persistent<v8::Object>::New(wrapper));
    return wrapper;
}

v8::Handle<v8::Value> toV8(PassRefPtr<HTMLCanvasElement > impl, bool forceNewObject)
{
    return toV8(impl.get(), forceNewObject);
}

v8::Handle<v8::Value> toV8(HTMLCanvasElement* impl, bool forceNewObject)
{
    if (!impl)
        return v8::Null();
    return V8HTMLCanvasElement::wrap(impl, forceNewObject);
}

void V8HTMLCanvasElement::derefObject(void* object)
{
    static_cast<HTMLCanvasElement*>(object)->deref();
}

} // namespace WebCore
