/*
    This file is part of the WebKit open source project.
    This file has been generated by generate-bindings.pl. DO NOT MODIFY!

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Library General Public
    License as published by the Free Software Foundation; either
    version 2 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Library General Public License for more details.

    You should have received a copy of the GNU Library General Public License
    along with this library; see the file COPYING.LIB.  If not, write to
    the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
    Boston, MA 02111-1307, USA.
*/

#include "config.h"
#include "V8SVGPathSegCurvetoCubicAbs.h"

#if ENABLE(SVG)

#include "RuntimeEnabledFeatures.h"
#include "SVGElement.h"
#include "SVGPathSegCurvetoCubic.h"
#include "V8Binding.h"
#include "V8BindingState.h"
#include "V8DOMWrapper.h"
#include "V8IsolatedContext.h"
#include "V8Proxy.h"
#include "V8SVGPathSeg.h"

namespace WebCore {

WrapperTypeInfo V8SVGPathSegCurvetoCubicAbs::info = { V8SVGPathSegCurvetoCubicAbs::GetTemplate, V8SVGPathSegCurvetoCubicAbs::derefObject, 0 };

namespace SVGPathSegCurvetoCubicAbsInternal {

template <typename T> void V8_USE(T) { }

static v8::Handle<v8::Value> xAttrGetter(v8::Local<v8::String> name, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.SVGPathSegCurvetoCubicAbs.x._get");
    SVGPathSegCurvetoCubicAbs* imp = V8SVGPathSegCurvetoCubicAbs::toNative(info.Holder());
    return v8::Number::New(imp->x());
}

static void xAttrSetter(v8::Local<v8::String> name, v8::Local<v8::Value> value, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.SVGPathSegCurvetoCubicAbs.x._set");
    SVGPathSegCurvetoCubicAbs* imp = V8SVGPathSegCurvetoCubicAbs::toNative(info.Holder());
    float v = static_cast<float>(value->NumberValue());
    imp->setX(v);
    if (SVGElement* context = V8Proxy::svgContext(imp))
        context->svgAttributeChanged(imp->associatedAttributeName());
    return;
}

static v8::Handle<v8::Value> yAttrGetter(v8::Local<v8::String> name, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.SVGPathSegCurvetoCubicAbs.y._get");
    SVGPathSegCurvetoCubicAbs* imp = V8SVGPathSegCurvetoCubicAbs::toNative(info.Holder());
    return v8::Number::New(imp->y());
}

static void yAttrSetter(v8::Local<v8::String> name, v8::Local<v8::Value> value, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.SVGPathSegCurvetoCubicAbs.y._set");
    SVGPathSegCurvetoCubicAbs* imp = V8SVGPathSegCurvetoCubicAbs::toNative(info.Holder());
    float v = static_cast<float>(value->NumberValue());
    imp->setY(v);
    if (SVGElement* context = V8Proxy::svgContext(imp))
        context->svgAttributeChanged(imp->associatedAttributeName());
    return;
}

static v8::Handle<v8::Value> x1AttrGetter(v8::Local<v8::String> name, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.SVGPathSegCurvetoCubicAbs.x1._get");
    SVGPathSegCurvetoCubicAbs* imp = V8SVGPathSegCurvetoCubicAbs::toNative(info.Holder());
    return v8::Number::New(imp->x1());
}

static void x1AttrSetter(v8::Local<v8::String> name, v8::Local<v8::Value> value, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.SVGPathSegCurvetoCubicAbs.x1._set");
    SVGPathSegCurvetoCubicAbs* imp = V8SVGPathSegCurvetoCubicAbs::toNative(info.Holder());
    float v = static_cast<float>(value->NumberValue());
    imp->setX1(v);
    if (SVGElement* context = V8Proxy::svgContext(imp))
        context->svgAttributeChanged(imp->associatedAttributeName());
    return;
}

static v8::Handle<v8::Value> y1AttrGetter(v8::Local<v8::String> name, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.SVGPathSegCurvetoCubicAbs.y1._get");
    SVGPathSegCurvetoCubicAbs* imp = V8SVGPathSegCurvetoCubicAbs::toNative(info.Holder());
    return v8::Number::New(imp->y1());
}

static void y1AttrSetter(v8::Local<v8::String> name, v8::Local<v8::Value> value, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.SVGPathSegCurvetoCubicAbs.y1._set");
    SVGPathSegCurvetoCubicAbs* imp = V8SVGPathSegCurvetoCubicAbs::toNative(info.Holder());
    float v = static_cast<float>(value->NumberValue());
    imp->setY1(v);
    if (SVGElement* context = V8Proxy::svgContext(imp))
        context->svgAttributeChanged(imp->associatedAttributeName());
    return;
}

static v8::Handle<v8::Value> x2AttrGetter(v8::Local<v8::String> name, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.SVGPathSegCurvetoCubicAbs.x2._get");
    SVGPathSegCurvetoCubicAbs* imp = V8SVGPathSegCurvetoCubicAbs::toNative(info.Holder());
    return v8::Number::New(imp->x2());
}

static void x2AttrSetter(v8::Local<v8::String> name, v8::Local<v8::Value> value, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.SVGPathSegCurvetoCubicAbs.x2._set");
    SVGPathSegCurvetoCubicAbs* imp = V8SVGPathSegCurvetoCubicAbs::toNative(info.Holder());
    float v = static_cast<float>(value->NumberValue());
    imp->setX2(v);
    if (SVGElement* context = V8Proxy::svgContext(imp))
        context->svgAttributeChanged(imp->associatedAttributeName());
    return;
}

static v8::Handle<v8::Value> y2AttrGetter(v8::Local<v8::String> name, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.SVGPathSegCurvetoCubicAbs.y2._get");
    SVGPathSegCurvetoCubicAbs* imp = V8SVGPathSegCurvetoCubicAbs::toNative(info.Holder());
    return v8::Number::New(imp->y2());
}

static void y2AttrSetter(v8::Local<v8::String> name, v8::Local<v8::Value> value, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.SVGPathSegCurvetoCubicAbs.y2._set");
    SVGPathSegCurvetoCubicAbs* imp = V8SVGPathSegCurvetoCubicAbs::toNative(info.Holder());
    float v = static_cast<float>(value->NumberValue());
    imp->setY2(v);
    if (SVGElement* context = V8Proxy::svgContext(imp))
        context->svgAttributeChanged(imp->associatedAttributeName());
    return;
}

} // namespace SVGPathSegCurvetoCubicAbsInternal

static const BatchedAttribute SVGPathSegCurvetoCubicAbsAttrs[] = {
    // Attribute 'x' (Type: 'attribute' ExtAttr: '')
    {"x", SVGPathSegCurvetoCubicAbsInternal::xAttrGetter, SVGPathSegCurvetoCubicAbsInternal::xAttrSetter, 0 /* no data */, static_cast<v8::AccessControl>(v8::DEFAULT), static_cast<v8::PropertyAttribute>(v8::None), 0 /* on instance */},
    // Attribute 'y' (Type: 'attribute' ExtAttr: '')
    {"y", SVGPathSegCurvetoCubicAbsInternal::yAttrGetter, SVGPathSegCurvetoCubicAbsInternal::yAttrSetter, 0 /* no data */, static_cast<v8::AccessControl>(v8::DEFAULT), static_cast<v8::PropertyAttribute>(v8::None), 0 /* on instance */},
    // Attribute 'x1' (Type: 'attribute' ExtAttr: '')
    {"x1", SVGPathSegCurvetoCubicAbsInternal::x1AttrGetter, SVGPathSegCurvetoCubicAbsInternal::x1AttrSetter, 0 /* no data */, static_cast<v8::AccessControl>(v8::DEFAULT), static_cast<v8::PropertyAttribute>(v8::None), 0 /* on instance */},
    // Attribute 'y1' (Type: 'attribute' ExtAttr: '')
    {"y1", SVGPathSegCurvetoCubicAbsInternal::y1AttrGetter, SVGPathSegCurvetoCubicAbsInternal::y1AttrSetter, 0 /* no data */, static_cast<v8::AccessControl>(v8::DEFAULT), static_cast<v8::PropertyAttribute>(v8::None), 0 /* on instance */},
    // Attribute 'x2' (Type: 'attribute' ExtAttr: '')
    {"x2", SVGPathSegCurvetoCubicAbsInternal::x2AttrGetter, SVGPathSegCurvetoCubicAbsInternal::x2AttrSetter, 0 /* no data */, static_cast<v8::AccessControl>(v8::DEFAULT), static_cast<v8::PropertyAttribute>(v8::None), 0 /* on instance */},
    // Attribute 'y2' (Type: 'attribute' ExtAttr: '')
    {"y2", SVGPathSegCurvetoCubicAbsInternal::y2AttrGetter, SVGPathSegCurvetoCubicAbsInternal::y2AttrSetter, 0 /* no data */, static_cast<v8::AccessControl>(v8::DEFAULT), static_cast<v8::PropertyAttribute>(v8::None), 0 /* on instance */},
};
static v8::Persistent<v8::FunctionTemplate> ConfigureV8SVGPathSegCurvetoCubicAbsTemplate(v8::Persistent<v8::FunctionTemplate> desc)
{
    v8::Local<v8::Signature> defaultSignature = configureTemplate(desc, "SVGPathSegCurvetoCubicAbs", V8SVGPathSeg::GetTemplate(), V8SVGPathSegCurvetoCubicAbs::internalFieldCount,
        SVGPathSegCurvetoCubicAbsAttrs, sizeof(SVGPathSegCurvetoCubicAbsAttrs) / sizeof(*SVGPathSegCurvetoCubicAbsAttrs),
        0, 0);
    

    // Custom toString template
    desc->Set(getToStringName(), getToStringTemplate());
    return desc;
}

v8::Persistent<v8::FunctionTemplate> V8SVGPathSegCurvetoCubicAbs::GetRawTemplate()
{
    static v8::Persistent<v8::FunctionTemplate> V8SVGPathSegCurvetoCubicAbsRawCache = createRawTemplate();
    return V8SVGPathSegCurvetoCubicAbsRawCache;
}

v8::Persistent<v8::FunctionTemplate> V8SVGPathSegCurvetoCubicAbs::GetTemplate()
{
    static v8::Persistent<v8::FunctionTemplate> V8SVGPathSegCurvetoCubicAbsCache = ConfigureV8SVGPathSegCurvetoCubicAbsTemplate(GetRawTemplate());
    return V8SVGPathSegCurvetoCubicAbsCache;
}

SVGPathSegCurvetoCubicAbs* V8SVGPathSegCurvetoCubicAbs::toNative(v8::Handle<v8::Object> object)
{
    return reinterpret_cast<SVGPathSegCurvetoCubicAbs*>(object->GetPointerFromInternalField(v8DOMWrapperObjectIndex));
}

bool V8SVGPathSegCurvetoCubicAbs::HasInstance(v8::Handle<v8::Value> value)
{
    return GetRawTemplate()->HasInstance(value);
}


v8::Handle<v8::Object> V8SVGPathSegCurvetoCubicAbs::wrap(SVGPathSegCurvetoCubicAbs* impl)
{
    v8::Handle<v8::Object> wrapper;
    V8Proxy* proxy = 0;
        wrapper = getDOMSVGObjectWithContextMap().get(impl);
        if (!wrapper.IsEmpty())
            return wrapper;
    wrapper = V8DOMWrapper::instantiateV8Object(proxy, &info, impl);
    if (wrapper.IsEmpty())
        return wrapper;

    impl->ref();
    getDOMSVGObjectWithContextMap().set(impl, v8::Persistent<v8::Object>::New(wrapper));
    return wrapper;
}

v8::Handle<v8::Value> toV8(PassRefPtr<SVGPathSegCurvetoCubicAbs > impl)
{
    return toV8(impl.get());
}

v8::Handle<v8::Value> toV8(SVGPathSegCurvetoCubicAbs* impl)
{
    if (!impl)
        return v8::Null();
    return V8SVGPathSegCurvetoCubicAbs::wrap(impl);
}

void V8SVGPathSegCurvetoCubicAbs::derefObject(void* object)
{
    static_cast<SVGPathSegCurvetoCubicAbs*>(object)->deref();
}

} // namespace WebCore

#endif // ENABLE(SVG)
