/*
    This file is part of the WebKit open source project.
    This file has been generated by generate-bindings.pl. DO NOT MODIFY!

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Library General Public
    License as published by the Free Software Foundation; either
    version 2 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Library General Public License for more details.

    You should have received a copy of the GNU Library General Public License
    along with this library; see the file COPYING.LIB.  If not, write to
    the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
    Boston, MA 02111-1307, USA.
*/

#include "config.h"
#include "V8SVGNumberList.h"

#if ENABLE(SVG)

#include "ExceptionCode.h"
#include "RuntimeEnabledFeatures.h"
#include "SVGElement.h"
#include "V8Binding.h"
#include "V8BindingMacros.h"
#include "V8BindingState.h"
#include "V8DOMWrapper.h"
#include "V8IsolatedContext.h"
#include "V8Proxy.h"
#include "V8SVGNumber.h"
#include "V8SVGPODTypeWrapper.h"

namespace WebCore {

WrapperTypeInfo V8SVGNumberList::info = { V8SVGNumberList::GetTemplate, V8SVGNumberList::derefObject, 0 };

namespace SVGNumberListInternal {

template <typename T> void V8_USE(T) { }

static v8::Handle<v8::Value> numberOfItemsAttrGetter(v8::Local<v8::String> name, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.SVGNumberList.numberOfItems._get");
    SVGNumberList* imp = V8SVGNumberList::toNative(info.Holder());
    return v8::Integer::NewFromUnsigned(imp->numberOfItems());
}

static v8::Handle<v8::Value> clearCallback(const v8::Arguments& args)
{
    INC_STATS("DOM.SVGNumberList.clear");
    SVGNumberList* imp = V8SVGNumberList::toNative(args.Holder());
    ExceptionCode ec = 0;
    {
    imp->clear(ec);
    if (UNLIKELY(ec))
        goto fail;
    SVGElement* context = V8Proxy::svgContext(imp);
    context->svgAttributeChanged(imp->associatedAttributeName());
    return v8::Handle<v8::Value>();
    }
    fail:
    V8Proxy::setDOMException(ec);
    return v8::Handle<v8::Value>();
}

static v8::Handle<v8::Value> initializeCallback(const v8::Arguments& args)
{
    INC_STATS("DOM.SVGNumberList.initialize");
    SVGNumberList* imp = V8SVGNumberList::toNative(args.Holder());
    ExceptionCode ec = 0;
    {
    EXCEPTION_BLOCK(float, item, args[0]->NumberValue());
    float result = imp->initialize(item, ec);
    if (UNLIKELY(ec))
        goto fail;
    RefPtr<V8SVGPODTypeWrapper<float> > wrapper = V8SVGStaticPODTypeWrapper<float>::create(result);
    SVGElement* context = V8Proxy::svgContext(imp);
    V8Proxy::setSVGContext(wrapper.get(), context);
    context->svgAttributeChanged(imp->associatedAttributeName());
    return toV8(wrapper.release());
    }
    fail:
    V8Proxy::setDOMException(ec);
    return v8::Handle<v8::Value>();
}

static v8::Handle<v8::Value> getItemCallback(const v8::Arguments& args)
{
    INC_STATS("DOM.SVGNumberList.getItem");
    SVGNumberList* imp = V8SVGNumberList::toNative(args.Holder());
    ExceptionCode ec = 0;
    {
    EXCEPTION_BLOCK(unsigned, index, toUInt32(args[0]));
    float result = imp->getItem(index, ec);
    if (UNLIKELY(ec))
        goto fail;
    RefPtr<V8SVGPODTypeWrapper<float> > wrapper = V8SVGStaticPODTypeWrapper<float>::create(result);
    SVGElement* context = V8Proxy::svgContext(imp);
    V8Proxy::setSVGContext(wrapper.get(), context);
    return toV8(wrapper.release());
    }
    fail:
    V8Proxy::setDOMException(ec);
    return v8::Handle<v8::Value>();
}

static v8::Handle<v8::Value> insertItemBeforeCallback(const v8::Arguments& args)
{
    INC_STATS("DOM.SVGNumberList.insertItemBefore");
    SVGNumberList* imp = V8SVGNumberList::toNative(args.Holder());
    ExceptionCode ec = 0;
    {
    EXCEPTION_BLOCK(float, item, args[0]->NumberValue());
    EXCEPTION_BLOCK(unsigned, index, toUInt32(args[1]));
    float result = imp->insertItemBefore(item, index, ec);
    if (UNLIKELY(ec))
        goto fail;
    RefPtr<V8SVGPODTypeWrapper<float> > wrapper = V8SVGStaticPODTypeWrapper<float>::create(result);
    SVGElement* context = V8Proxy::svgContext(imp);
    V8Proxy::setSVGContext(wrapper.get(), context);
    context->svgAttributeChanged(imp->associatedAttributeName());
    return toV8(wrapper.release());
    }
    fail:
    V8Proxy::setDOMException(ec);
    return v8::Handle<v8::Value>();
}

static v8::Handle<v8::Value> replaceItemCallback(const v8::Arguments& args)
{
    INC_STATS("DOM.SVGNumberList.replaceItem");
    SVGNumberList* imp = V8SVGNumberList::toNative(args.Holder());
    ExceptionCode ec = 0;
    {
    EXCEPTION_BLOCK(float, item, args[0]->NumberValue());
    EXCEPTION_BLOCK(unsigned, index, toUInt32(args[1]));
    float result = imp->replaceItem(item, index, ec);
    if (UNLIKELY(ec))
        goto fail;
    RefPtr<V8SVGPODTypeWrapper<float> > wrapper = V8SVGStaticPODTypeWrapper<float>::create(result);
    SVGElement* context = V8Proxy::svgContext(imp);
    V8Proxy::setSVGContext(wrapper.get(), context);
    context->svgAttributeChanged(imp->associatedAttributeName());
    return toV8(wrapper.release());
    }
    fail:
    V8Proxy::setDOMException(ec);
    return v8::Handle<v8::Value>();
}

static v8::Handle<v8::Value> removeItemCallback(const v8::Arguments& args)
{
    INC_STATS("DOM.SVGNumberList.removeItem");
    SVGNumberList* imp = V8SVGNumberList::toNative(args.Holder());
    ExceptionCode ec = 0;
    {
    EXCEPTION_BLOCK(unsigned, index, toUInt32(args[0]));
    float result = imp->removeItem(index, ec);
    if (UNLIKELY(ec))
        goto fail;
    RefPtr<V8SVGPODTypeWrapper<float> > wrapper = V8SVGStaticPODTypeWrapper<float>::create(result);
    SVGElement* context = V8Proxy::svgContext(imp);
    V8Proxy::setSVGContext(wrapper.get(), context);
    context->svgAttributeChanged(imp->associatedAttributeName());
    return toV8(wrapper.release());
    }
    fail:
    V8Proxy::setDOMException(ec);
    return v8::Handle<v8::Value>();
}

static v8::Handle<v8::Value> appendItemCallback(const v8::Arguments& args)
{
    INC_STATS("DOM.SVGNumberList.appendItem");
    SVGNumberList* imp = V8SVGNumberList::toNative(args.Holder());
    ExceptionCode ec = 0;
    {
    EXCEPTION_BLOCK(float, item, args[0]->NumberValue());
    float result = imp->appendItem(item, ec);
    if (UNLIKELY(ec))
        goto fail;
    RefPtr<V8SVGPODTypeWrapper<float> > wrapper = V8SVGStaticPODTypeWrapper<float>::create(result);
    SVGElement* context = V8Proxy::svgContext(imp);
    V8Proxy::setSVGContext(wrapper.get(), context);
    context->svgAttributeChanged(imp->associatedAttributeName());
    return toV8(wrapper.release());
    }
    fail:
    V8Proxy::setDOMException(ec);
    return v8::Handle<v8::Value>();
}

} // namespace SVGNumberListInternal

static const BatchedAttribute SVGNumberListAttrs[] = {
    // Attribute 'numberOfItems' (Type: 'readonly attribute' ExtAttr: '')
    {"numberOfItems", SVGNumberListInternal::numberOfItemsAttrGetter, 0, 0 /* no data */, static_cast<v8::AccessControl>(v8::DEFAULT), static_cast<v8::PropertyAttribute>(v8::None), 0 /* on instance */},
};
static const BatchedCallback SVGNumberListCallbacks[] = {
    {"clear", SVGNumberListInternal::clearCallback},
    {"initialize", SVGNumberListInternal::initializeCallback},
    {"getItem", SVGNumberListInternal::getItemCallback},
    {"insertItemBefore", SVGNumberListInternal::insertItemBeforeCallback},
    {"replaceItem", SVGNumberListInternal::replaceItemCallback},
    {"removeItem", SVGNumberListInternal::removeItemCallback},
    {"appendItem", SVGNumberListInternal::appendItemCallback},
};
static v8::Persistent<v8::FunctionTemplate> ConfigureV8SVGNumberListTemplate(v8::Persistent<v8::FunctionTemplate> desc)
{
    v8::Local<v8::Signature> defaultSignature = configureTemplate(desc, "SVGNumberList", v8::Persistent<v8::FunctionTemplate>(), V8SVGNumberList::internalFieldCount,
        SVGNumberListAttrs, sizeof(SVGNumberListAttrs) / sizeof(*SVGNumberListAttrs),
        SVGNumberListCallbacks, sizeof(SVGNumberListCallbacks) / sizeof(*SVGNumberListCallbacks));
    v8::Local<v8::ObjectTemplate> instance = desc->InstanceTemplate();
    v8::Local<v8::ObjectTemplate> proto = desc->PrototypeTemplate();
    

    // Custom toString template
    desc->Set(getToStringName(), getToStringTemplate());
    return desc;
}

v8::Persistent<v8::FunctionTemplate> V8SVGNumberList::GetRawTemplate()
{
    static v8::Persistent<v8::FunctionTemplate> V8SVGNumberListRawCache = createRawTemplate();
    return V8SVGNumberListRawCache;
}

v8::Persistent<v8::FunctionTemplate> V8SVGNumberList::GetTemplate()
{
    static v8::Persistent<v8::FunctionTemplate> V8SVGNumberListCache = ConfigureV8SVGNumberListTemplate(GetRawTemplate());
    return V8SVGNumberListCache;
}

SVGNumberList* V8SVGNumberList::toNative(v8::Handle<v8::Object> object)
{
    return reinterpret_cast<SVGNumberList*>(object->GetPointerFromInternalField(v8DOMWrapperObjectIndex));
}

bool V8SVGNumberList::HasInstance(v8::Handle<v8::Value> value)
{
    return GetRawTemplate()->HasInstance(value);
}


v8::Handle<v8::Object> V8SVGNumberList::wrap(SVGNumberList* impl)
{
    v8::Handle<v8::Object> wrapper;
    V8Proxy* proxy = 0;
        wrapper = getDOMSVGObjectWithContextMap().get(impl);
        if (!wrapper.IsEmpty())
            return wrapper;
    wrapper = V8DOMWrapper::instantiateV8Object(proxy, &info, impl);
    if (wrapper.IsEmpty())
        return wrapper;

    impl->ref();
    getDOMSVGObjectWithContextMap().set(impl, v8::Persistent<v8::Object>::New(wrapper));
    return wrapper;
}

v8::Handle<v8::Value> toV8(PassRefPtr<SVGNumberList > impl)
{
    return toV8(impl.get());
}

v8::Handle<v8::Value> toV8(SVGNumberList* impl)
{
    if (!impl)
        return v8::Null();
    return V8SVGNumberList::wrap(impl);
}

void V8SVGNumberList::derefObject(void* object)
{
    static_cast<SVGNumberList*>(object)->deref();
}

} // namespace WebCore

#endif // ENABLE(SVG)
