/*
    This file is part of the WebKit open source project.
    This file has been generated by generate-bindings.pl. DO NOT MODIFY!

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Library General Public
    License as published by the Free Software Foundation; either
    version 2 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Library General Public License for more details.

    You should have received a copy of the GNU Library General Public License
    along with this library; see the file COPYING.LIB.  If not, write to
    the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
    Boston, MA 02111-1307, USA.
*/

#include "config.h"
#include "V8SVGGradientElement.h"

#if ENABLE(SVG)

#include "CSSMutableStyleDeclaration.h"
#include "ExceptionCode.h"
#include "RuntimeEnabledFeatures.h"
#include "V8Binding.h"
#include "V8BindingMacros.h"
#include "V8BindingState.h"
#include "V8CSSStyleDeclaration.h"
#include "V8CSSValue.h"
#include "V8DOMWrapper.h"
#include "V8IsolatedContext.h"
#include "V8Proxy.h"
#include "V8SVGAnimatedBoolean.h"
#include "V8SVGAnimatedEnumeration.h"
#include "V8SVGAnimatedString.h"
#include "V8SVGAnimatedTransformList.h"
#include "V8SVGElement.h"
#include <wtf/GetPtr.h>
#include <wtf/RefCounted.h>
#include <wtf/RefPtr.h>

namespace WebCore {

WrapperTypeInfo V8SVGGradientElement::info = { V8SVGGradientElement::GetTemplate, V8SVGGradientElement::derefObject, 0 };

namespace SVGGradientElementInternal {

template <typename T> void V8_USE(T) { }

static v8::Handle<v8::Value> gradientUnitsAttrGetter(v8::Local<v8::String> name, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.SVGGradientElement.gradientUnits._get");
    SVGGradientElement* imp = V8SVGGradientElement::toNative(info.Holder());
    SVGElement* context = imp;
    PassRefPtr<SVGAnimatedEnumeration> resultAsPassRefPtr = V8Proxy::withSVGContext(imp->gradientUnitsAnimated(), context);
    return toV8(resultAsPassRefPtr);
}

static v8::Handle<v8::Value> gradientTransformAttrGetter(v8::Local<v8::String> name, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.SVGGradientElement.gradientTransform._get");
    SVGGradientElement* imp = V8SVGGradientElement::toNative(info.Holder());
    SVGElement* context = imp;
    PassRefPtr<SVGAnimatedTransformList> resultAsPassRefPtr = V8Proxy::withSVGContext(imp->gradientTransformAnimated(), context);
    return toV8(resultAsPassRefPtr);
}

static v8::Handle<v8::Value> spreadMethodAttrGetter(v8::Local<v8::String> name, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.SVGGradientElement.spreadMethod._get");
    SVGGradientElement* imp = V8SVGGradientElement::toNative(info.Holder());
    SVGElement* context = imp;
    PassRefPtr<SVGAnimatedEnumeration> resultAsPassRefPtr = V8Proxy::withSVGContext(imp->spreadMethodAnimated(), context);
    return toV8(resultAsPassRefPtr);
}

static v8::Handle<v8::Value> hrefAttrGetter(v8::Local<v8::String> name, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.SVGGradientElement.href._get");
    SVGGradientElement* imp = V8SVGGradientElement::toNative(info.Holder());
    SVGElement* context = imp;
    PassRefPtr<SVGAnimatedString> resultAsPassRefPtr = V8Proxy::withSVGContext(imp->hrefAnimated(), context);
    return toV8(resultAsPassRefPtr);
}

static v8::Handle<v8::Value> externalResourcesRequiredAttrGetter(v8::Local<v8::String> name, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.SVGGradientElement.externalResourcesRequired._get");
    SVGGradientElement* imp = V8SVGGradientElement::toNative(info.Holder());
    SVGElement* context = imp;
    PassRefPtr<SVGAnimatedBoolean> resultAsPassRefPtr = V8Proxy::withSVGContext(imp->externalResourcesRequiredAnimated(), context);
    return toV8(resultAsPassRefPtr);
}

static v8::Handle<v8::Value> classNameAttrGetter(v8::Local<v8::String> name, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.SVGGradientElement.className._get");
    SVGGradientElement* imp = V8SVGGradientElement::toNative(info.Holder());
    SVGElement* context = imp;
    PassRefPtr<SVGAnimatedString> resultAsPassRefPtr = V8Proxy::withSVGContext(imp->classNameAnimated(), context);
    return toV8(resultAsPassRefPtr);
}

static v8::Handle<v8::Value> styleAttrGetter(v8::Local<v8::String> name, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.SVGGradientElement.style._get");
    SVGGradientElement* imp = V8SVGGradientElement::toNative(info.Holder());
    return toV8(imp->style());
}

static v8::Handle<v8::Value> getPresentationAttributeCallback(const v8::Arguments& args)
{
    INC_STATS("DOM.SVGGradientElement.getPresentationAttribute");
    SVGGradientElement* imp = V8SVGGradientElement::toNative(args.Holder());
    STRING_TO_V8PARAMETER_EXCEPTION_BLOCK(V8Parameter<>, name, args[0]);
    return toV8(imp->getPresentationAttribute(name));
}

} // namespace SVGGradientElementInternal

static const BatchedAttribute SVGGradientElementAttrs[] = {
    // Attribute 'gradientUnits' (Type: 'readonly attribute' ExtAttr: '')
    {"gradientUnits", SVGGradientElementInternal::gradientUnitsAttrGetter, 0, 0 /* no data */, static_cast<v8::AccessControl>(v8::DEFAULT), static_cast<v8::PropertyAttribute>(v8::None), 0 /* on instance */},
    // Attribute 'gradientTransform' (Type: 'readonly attribute' ExtAttr: '')
    {"gradientTransform", SVGGradientElementInternal::gradientTransformAttrGetter, 0, 0 /* no data */, static_cast<v8::AccessControl>(v8::DEFAULT), static_cast<v8::PropertyAttribute>(v8::None), 0 /* on instance */},
    // Attribute 'spreadMethod' (Type: 'readonly attribute' ExtAttr: '')
    {"spreadMethod", SVGGradientElementInternal::spreadMethodAttrGetter, 0, 0 /* no data */, static_cast<v8::AccessControl>(v8::DEFAULT), static_cast<v8::PropertyAttribute>(v8::None), 0 /* on instance */},
    // Attribute 'href' (Type: 'readonly attribute' ExtAttr: '')
    {"href", SVGGradientElementInternal::hrefAttrGetter, 0, 0 /* no data */, static_cast<v8::AccessControl>(v8::DEFAULT), static_cast<v8::PropertyAttribute>(v8::None), 0 /* on instance */},
    // Attribute 'externalResourcesRequired' (Type: 'readonly attribute' ExtAttr: '')
    {"externalResourcesRequired", SVGGradientElementInternal::externalResourcesRequiredAttrGetter, 0, 0 /* no data */, static_cast<v8::AccessControl>(v8::DEFAULT), static_cast<v8::PropertyAttribute>(v8::None), 0 /* on instance */},
    // Attribute 'className' (Type: 'readonly attribute' ExtAttr: '')
    {"className", SVGGradientElementInternal::classNameAttrGetter, 0, 0 /* no data */, static_cast<v8::AccessControl>(v8::DEFAULT), static_cast<v8::PropertyAttribute>(v8::None), 0 /* on instance */},
    // Attribute 'style' (Type: 'readonly attribute' ExtAttr: '')
    {"style", SVGGradientElementInternal::styleAttrGetter, 0, 0 /* no data */, static_cast<v8::AccessControl>(v8::DEFAULT), static_cast<v8::PropertyAttribute>(v8::None), 0 /* on instance */},
};
static const BatchedCallback SVGGradientElementCallbacks[] = {
    {"getPresentationAttribute", SVGGradientElementInternal::getPresentationAttributeCallback},
};
static const BatchedConstant SVGGradientElementConsts[] = {
    {"SVG_SPREADMETHOD_UNKNOWN", static_cast<signed int>(0)},
    {"SVG_SPREADMETHOD_PAD", static_cast<signed int>(1)},
    {"SVG_SPREADMETHOD_REFLECT", static_cast<signed int>(2)},
    {"SVG_SPREADMETHOD_REPEAT", static_cast<signed int>(3)},
};
static v8::Persistent<v8::FunctionTemplate> ConfigureV8SVGGradientElementTemplate(v8::Persistent<v8::FunctionTemplate> desc)
{
    v8::Local<v8::Signature> defaultSignature = configureTemplate(desc, "SVGGradientElement", V8SVGElement::GetTemplate(), V8SVGGradientElement::internalFieldCount,
        SVGGradientElementAttrs, sizeof(SVGGradientElementAttrs) / sizeof(*SVGGradientElementAttrs),
        SVGGradientElementCallbacks, sizeof(SVGGradientElementCallbacks) / sizeof(*SVGGradientElementCallbacks));
    v8::Local<v8::ObjectTemplate> instance = desc->InstanceTemplate();
    v8::Local<v8::ObjectTemplate> proto = desc->PrototypeTemplate();
    
    batchConfigureConstants(desc, proto, SVGGradientElementConsts, sizeof(SVGGradientElementConsts) / sizeof(*SVGGradientElementConsts));

    // Custom toString template
    desc->Set(getToStringName(), getToStringTemplate());
    return desc;
}

v8::Persistent<v8::FunctionTemplate> V8SVGGradientElement::GetRawTemplate()
{
    static v8::Persistent<v8::FunctionTemplate> V8SVGGradientElementRawCache = createRawTemplate();
    return V8SVGGradientElementRawCache;
}

v8::Persistent<v8::FunctionTemplate> V8SVGGradientElement::GetTemplate()
{
    static v8::Persistent<v8::FunctionTemplate> V8SVGGradientElementCache = ConfigureV8SVGGradientElementTemplate(GetRawTemplate());
    return V8SVGGradientElementCache;
}

SVGGradientElement* V8SVGGradientElement::toNative(v8::Handle<v8::Object> object)
{
    return reinterpret_cast<SVGGradientElement*>(object->GetPointerFromInternalField(v8DOMWrapperObjectIndex));
}

bool V8SVGGradientElement::HasInstance(v8::Handle<v8::Value> value)
{
    return GetRawTemplate()->HasInstance(value);
}


v8::Handle<v8::Object> V8SVGGradientElement::wrap(SVGGradientElement* impl)
{
    v8::Handle<v8::Object> wrapper;
    V8Proxy* proxy = 0;
    if (impl->document()) {
        proxy = V8Proxy::retrieve(impl->document()->frame());
        if (proxy && static_cast<Node*>(impl->document()) == static_cast<Node*>(impl))
            proxy->windowShell()->initContextIfNeeded();
    }

        wrapper = V8DOMWrapper::getWrapper(impl);
        if (!wrapper.IsEmpty())
            return wrapper;

    v8::Handle<v8::Context> context;
    if (proxy)
        context = proxy->context();

    // Enter the node's context and create the wrapper in that context.
    if (!context.IsEmpty())
        context->Enter();
    wrapper = V8DOMWrapper::instantiateV8Object(proxy, &info, impl);
    // Exit the node's context if it was entered.
    if (!context.IsEmpty())
        context->Exit();
    if (wrapper.IsEmpty())
        return wrapper;

    impl->ref();
    getDOMNodeMap().set(impl, v8::Persistent<v8::Object>::New(wrapper));
    return wrapper;
}

v8::Handle<v8::Value> toV8(PassRefPtr<SVGGradientElement > impl)
{
    return toV8(impl.get());
}

v8::Handle<v8::Value> toV8(SVGGradientElement* impl)
{
    if (!impl)
        return v8::Null();
    return V8SVGGradientElement::wrap(impl);
}

void V8SVGGradientElement::derefObject(void* object)
{
    static_cast<SVGGradientElement*>(object)->deref();
}

} // namespace WebCore

#endif // ENABLE(SVG)
