/*
    This file is part of the WebKit open source project.
    This file has been generated by generate-bindings.pl. DO NOT MODIFY!

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Library General Public
    License as published by the Free Software Foundation; either
    version 2 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Library General Public License for more details.

    You should have received a copy of the GNU Library General Public License
    along with this library; see the file COPYING.LIB.  If not, write to
    the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
    Boston, MA 02111-1307, USA.
*/

#include "config.h"
#include "V8SVGRect.h"

#if ENABLE(SVG)

#include "RuntimeEnabledFeatures.h"
#include "V8Binding.h"
#include "V8BindingState.h"
#include "V8DOMWrapper.h"
#include "V8IsolatedContext.h"
#include "V8Proxy.h"
#include "V8SVGPODTypeWrapper.h"

namespace WebCore {

WrapperTypeInfo V8SVGRect::info = { V8SVGRect::GetTemplate, V8SVGRect::derefObject, 0 };

namespace SVGRectInternal {

template <typename T> void V8_USE(T) { }

static v8::Handle<v8::Value> xAttrGetter(v8::Local<v8::String> name, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.FloatRect.x._get");
    V8SVGPODTypeWrapper<FloatRect>* impWrapper = V8SVGPODTypeWrapper<FloatRect>::toNative(info.Holder());
    FloatRect impInstance = *impWrapper;
    FloatRect* imp = &impInstance;
    return v8::Number::New(imp->x());
}

static void xAttrSetter(v8::Local<v8::String> name, v8::Local<v8::Value> value, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.SVGRect.x._set");
    V8SVGPODTypeWrapper<FloatRect>* wrapper = V8SVGPODTypeWrapper<FloatRect>::toNative(info.Holder());
    FloatRect impInstance = *wrapper;
    FloatRect* imp = &impInstance;
    float v = static_cast<float>(value->NumberValue());
    imp->setX(v);
    wrapper->commitChange(*imp, V8Proxy::svgContext(wrapper));
    return;
}

static v8::Handle<v8::Value> yAttrGetter(v8::Local<v8::String> name, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.FloatRect.y._get");
    V8SVGPODTypeWrapper<FloatRect>* impWrapper = V8SVGPODTypeWrapper<FloatRect>::toNative(info.Holder());
    FloatRect impInstance = *impWrapper;
    FloatRect* imp = &impInstance;
    return v8::Number::New(imp->y());
}

static void yAttrSetter(v8::Local<v8::String> name, v8::Local<v8::Value> value, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.SVGRect.y._set");
    V8SVGPODTypeWrapper<FloatRect>* wrapper = V8SVGPODTypeWrapper<FloatRect>::toNative(info.Holder());
    FloatRect impInstance = *wrapper;
    FloatRect* imp = &impInstance;
    float v = static_cast<float>(value->NumberValue());
    imp->setY(v);
    wrapper->commitChange(*imp, V8Proxy::svgContext(wrapper));
    return;
}

static v8::Handle<v8::Value> widthAttrGetter(v8::Local<v8::String> name, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.FloatRect.width._get");
    V8SVGPODTypeWrapper<FloatRect>* impWrapper = V8SVGPODTypeWrapper<FloatRect>::toNative(info.Holder());
    FloatRect impInstance = *impWrapper;
    FloatRect* imp = &impInstance;
    return v8::Number::New(imp->width());
}

static void widthAttrSetter(v8::Local<v8::String> name, v8::Local<v8::Value> value, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.SVGRect.width._set");
    V8SVGPODTypeWrapper<FloatRect>* wrapper = V8SVGPODTypeWrapper<FloatRect>::toNative(info.Holder());
    FloatRect impInstance = *wrapper;
    FloatRect* imp = &impInstance;
    float v = static_cast<float>(value->NumberValue());
    imp->setWidth(v);
    wrapper->commitChange(*imp, V8Proxy::svgContext(wrapper));
    return;
}

static v8::Handle<v8::Value> heightAttrGetter(v8::Local<v8::String> name, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.FloatRect.height._get");
    V8SVGPODTypeWrapper<FloatRect>* impWrapper = V8SVGPODTypeWrapper<FloatRect>::toNative(info.Holder());
    FloatRect impInstance = *impWrapper;
    FloatRect* imp = &impInstance;
    return v8::Number::New(imp->height());
}

static void heightAttrSetter(v8::Local<v8::String> name, v8::Local<v8::Value> value, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.SVGRect.height._set");
    V8SVGPODTypeWrapper<FloatRect>* wrapper = V8SVGPODTypeWrapper<FloatRect>::toNative(info.Holder());
    FloatRect impInstance = *wrapper;
    FloatRect* imp = &impInstance;
    float v = static_cast<float>(value->NumberValue());
    imp->setHeight(v);
    wrapper->commitChange(*imp, V8Proxy::svgContext(wrapper));
    return;
}

} // namespace SVGRectInternal

static const BatchedAttribute SVGRectAttrs[] = {
    // Attribute 'x' (Type: 'attribute' ExtAttr: '')
    {"x", SVGRectInternal::xAttrGetter, SVGRectInternal::xAttrSetter, 0 /* no data */, static_cast<v8::AccessControl>(v8::DEFAULT), static_cast<v8::PropertyAttribute>(v8::None), 0 /* on instance */},
    // Attribute 'y' (Type: 'attribute' ExtAttr: '')
    {"y", SVGRectInternal::yAttrGetter, SVGRectInternal::yAttrSetter, 0 /* no data */, static_cast<v8::AccessControl>(v8::DEFAULT), static_cast<v8::PropertyAttribute>(v8::None), 0 /* on instance */},
    // Attribute 'width' (Type: 'attribute' ExtAttr: '')
    {"width", SVGRectInternal::widthAttrGetter, SVGRectInternal::widthAttrSetter, 0 /* no data */, static_cast<v8::AccessControl>(v8::DEFAULT), static_cast<v8::PropertyAttribute>(v8::None), 0 /* on instance */},
    // Attribute 'height' (Type: 'attribute' ExtAttr: '')
    {"height", SVGRectInternal::heightAttrGetter, SVGRectInternal::heightAttrSetter, 0 /* no data */, static_cast<v8::AccessControl>(v8::DEFAULT), static_cast<v8::PropertyAttribute>(v8::None), 0 /* on instance */},
};
static v8::Persistent<v8::FunctionTemplate> ConfigureV8SVGRectTemplate(v8::Persistent<v8::FunctionTemplate> desc)
{
    v8::Local<v8::Signature> defaultSignature = configureTemplate(desc, "SVGRect", v8::Persistent<v8::FunctionTemplate>(), V8SVGRect::internalFieldCount,
        SVGRectAttrs, sizeof(SVGRectAttrs) / sizeof(*SVGRectAttrs),
        0, 0);
    

    // Custom toString template
    desc->Set(getToStringName(), getToStringTemplate());
    return desc;
}

v8::Persistent<v8::FunctionTemplate> V8SVGRect::GetRawTemplate()
{
    static v8::Persistent<v8::FunctionTemplate> V8SVGRectRawCache = createRawTemplate();
    return V8SVGRectRawCache;
}

v8::Persistent<v8::FunctionTemplate> V8SVGRect::GetTemplate()
{
    static v8::Persistent<v8::FunctionTemplate> V8SVGRectCache = ConfigureV8SVGRectTemplate(GetRawTemplate());
    return V8SVGRectCache;
}

V8SVGPODTypeWrapper<FloatRect>* V8SVGRect::toNative(v8::Handle<v8::Object> object)
{
    return reinterpret_cast<V8SVGPODTypeWrapper<FloatRect>*>(object->GetPointerFromInternalField(v8DOMWrapperObjectIndex));
}

bool V8SVGRect::HasInstance(v8::Handle<v8::Value> value)
{
    return GetRawTemplate()->HasInstance(value);
}


v8::Handle<v8::Object> V8SVGRect::wrap(V8SVGPODTypeWrapper<FloatRect>* impl)
{
    v8::Handle<v8::Object> wrapper;
    V8Proxy* proxy = 0;
        wrapper = getDOMSVGObjectWithContextMap().get(impl);
        if (!wrapper.IsEmpty())
            return wrapper;
    wrapper = V8DOMWrapper::instantiateV8Object(proxy, &info, impl);
    if (wrapper.IsEmpty())
        return wrapper;

    impl->ref();
    getDOMSVGObjectWithContextMap().set(impl, v8::Persistent<v8::Object>::New(wrapper));
    return wrapper;
}

v8::Handle<v8::Value> toV8(PassRefPtr<V8SVGPODTypeWrapper<FloatRect> > impl)
{
    return toV8(impl.get());
}

v8::Handle<v8::Value> toV8(V8SVGPODTypeWrapper<FloatRect>* impl)
{
    if (!impl)
        return v8::Null();
    return V8SVGRect::wrap(impl);
}

void V8SVGRect::derefObject(void* object)
{
    static_cast<V8SVGPODTypeWrapper<FloatRect>*>(object)->deref();
}

} // namespace WebCore

#endif // ENABLE(SVG)
