/*
    This file is part of the WebKit open source project.
    This file has been generated by generate-bindings.pl. DO NOT MODIFY!

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Library General Public
    License as published by the Free Software Foundation; either
    version 2 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Library General Public License for more details.

    You should have received a copy of the GNU Library General Public License
    along with this library; see the file COPYING.LIB.  If not, write to
    the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
    Boston, MA 02111-1307, USA.
*/

#include "config.h"
#include "V8SVGNumber.h"

#if ENABLE(SVG)

#include "RuntimeEnabledFeatures.h"
#include "V8Binding.h"
#include "V8BindingState.h"
#include "V8DOMWrapper.h"
#include "V8IsolatedContext.h"
#include "V8Proxy.h"
#include "V8SVGPODTypeWrapper.h"

namespace WebCore {

WrapperTypeInfo V8SVGNumber::info = { V8SVGNumber::GetTemplate, V8SVGNumber::derefObject, 0 };

namespace SVGNumberInternal {

template <typename T> void V8_USE(T) { }

static v8::Handle<v8::Value> valueAttrGetter(v8::Local<v8::String> name, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.float.value._get");
    V8SVGPODTypeWrapper<float>* impWrapper = V8SVGPODTypeWrapper<float>::toNative(info.Holder());
    float impInstance = *impWrapper;
    return v8::Number::New(impInstance);
}

static void valueAttrSetter(v8::Local<v8::String> name, v8::Local<v8::Value> value, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.SVGNumber.value._set");
    V8SVGPODTypeWrapper<float>* wrapper = V8SVGPODTypeWrapper<float>::toNative(info.Holder());
    float impInstance = *wrapper;
    float* imp = &impInstance;
    float v = static_cast<float>(value->NumberValue());
    *imp = v;
    wrapper->commitChange(*imp, V8Proxy::svgContext(wrapper));
    return;
}

} // namespace SVGNumberInternal

static const BatchedAttribute SVGNumberAttrs[] = {
    // Attribute 'value' (Type: 'attribute' ExtAttr: '')
    {"value", SVGNumberInternal::valueAttrGetter, SVGNumberInternal::valueAttrSetter, 0 /* no data */, static_cast<v8::AccessControl>(v8::DEFAULT), static_cast<v8::PropertyAttribute>(v8::None), 0 /* on instance */},
};
static v8::Persistent<v8::FunctionTemplate> ConfigureV8SVGNumberTemplate(v8::Persistent<v8::FunctionTemplate> desc)
{
    v8::Local<v8::Signature> defaultSignature = configureTemplate(desc, "SVGNumber", v8::Persistent<v8::FunctionTemplate>(), V8SVGNumber::internalFieldCount,
        SVGNumberAttrs, sizeof(SVGNumberAttrs) / sizeof(*SVGNumberAttrs),
        0, 0);
    

    // Custom toString template
    desc->Set(getToStringName(), getToStringTemplate());
    return desc;
}

v8::Persistent<v8::FunctionTemplate> V8SVGNumber::GetRawTemplate()
{
    static v8::Persistent<v8::FunctionTemplate> V8SVGNumberRawCache = createRawTemplate();
    return V8SVGNumberRawCache;
}

v8::Persistent<v8::FunctionTemplate> V8SVGNumber::GetTemplate()
{
    static v8::Persistent<v8::FunctionTemplate> V8SVGNumberCache = ConfigureV8SVGNumberTemplate(GetRawTemplate());
    return V8SVGNumberCache;
}

V8SVGPODTypeWrapper<float>* V8SVGNumber::toNative(v8::Handle<v8::Object> object)
{
    return reinterpret_cast<V8SVGPODTypeWrapper<float>*>(object->GetPointerFromInternalField(v8DOMWrapperObjectIndex));
}

bool V8SVGNumber::HasInstance(v8::Handle<v8::Value> value)
{
    return GetRawTemplate()->HasInstance(value);
}


v8::Handle<v8::Object> V8SVGNumber::wrap(V8SVGPODTypeWrapper<float>* impl)
{
    v8::Handle<v8::Object> wrapper;
    V8Proxy* proxy = 0;
        wrapper = getDOMSVGObjectWithContextMap().get(impl);
        if (!wrapper.IsEmpty())
            return wrapper;
    wrapper = V8DOMWrapper::instantiateV8Object(proxy, &info, impl);
    if (wrapper.IsEmpty())
        return wrapper;

    impl->ref();
    getDOMSVGObjectWithContextMap().set(impl, v8::Persistent<v8::Object>::New(wrapper));
    return wrapper;
}

v8::Handle<v8::Value> toV8(PassRefPtr<V8SVGPODTypeWrapper<float> > impl)
{
    return toV8(impl.get());
}

v8::Handle<v8::Value> toV8(V8SVGPODTypeWrapper<float>* impl)
{
    if (!impl)
        return v8::Null();
    return V8SVGNumber::wrap(impl);
}

void V8SVGNumber::derefObject(void* object)
{
    static_cast<V8SVGPODTypeWrapper<float>*>(object)->deref();
}

} // namespace WebCore

#endif // ENABLE(SVG)
