/*
    This file is part of the WebKit open source project.
    This file has been generated by generate-bindings.pl. DO NOT MODIFY!

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Library General Public
    License as published by the Free Software Foundation; either
    version 2 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Library General Public License for more details.

    You should have received a copy of the GNU Library General Public License
    along with this library; see the file COPYING.LIB.  If not, write to
    the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
    Boston, MA 02111-1307, USA.
*/

#include "config.h"
#include "V8SVGPathSegArcAbs.h"

#if ENABLE(SVG)

#include "RuntimeEnabledFeatures.h"
#include "SVGElement.h"
#include "SVGPathSegArc.h"
#include "V8Binding.h"
#include "V8BindingState.h"
#include "V8DOMWrapper.h"
#include "V8IsolatedContext.h"
#include "V8Proxy.h"
#include "V8SVGPathSeg.h"

namespace WebCore {

WrapperTypeInfo V8SVGPathSegArcAbs::info = { V8SVGPathSegArcAbs::GetTemplate, V8SVGPathSegArcAbs::derefObject, 0 };

namespace SVGPathSegArcAbsInternal {

template <typename T> void V8_USE(T) { }

static v8::Handle<v8::Value> xAttrGetter(v8::Local<v8::String> name, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.SVGPathSegArcAbs.x._get");
    SVGPathSegArcAbs* imp = V8SVGPathSegArcAbs::toNative(info.Holder());
    return v8::Number::New(imp->x());
}

static void xAttrSetter(v8::Local<v8::String> name, v8::Local<v8::Value> value, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.SVGPathSegArcAbs.x._set");
    SVGPathSegArcAbs* imp = V8SVGPathSegArcAbs::toNative(info.Holder());
    float v = static_cast<float>(value->NumberValue());
    imp->setX(v);
    if (SVGElement* context = V8Proxy::svgContext(imp))
        context->svgAttributeChanged(imp->associatedAttributeName());
    return;
}

static v8::Handle<v8::Value> yAttrGetter(v8::Local<v8::String> name, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.SVGPathSegArcAbs.y._get");
    SVGPathSegArcAbs* imp = V8SVGPathSegArcAbs::toNative(info.Holder());
    return v8::Number::New(imp->y());
}

static void yAttrSetter(v8::Local<v8::String> name, v8::Local<v8::Value> value, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.SVGPathSegArcAbs.y._set");
    SVGPathSegArcAbs* imp = V8SVGPathSegArcAbs::toNative(info.Holder());
    float v = static_cast<float>(value->NumberValue());
    imp->setY(v);
    if (SVGElement* context = V8Proxy::svgContext(imp))
        context->svgAttributeChanged(imp->associatedAttributeName());
    return;
}

static v8::Handle<v8::Value> r1AttrGetter(v8::Local<v8::String> name, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.SVGPathSegArcAbs.r1._get");
    SVGPathSegArcAbs* imp = V8SVGPathSegArcAbs::toNative(info.Holder());
    return v8::Number::New(imp->r1());
}

static void r1AttrSetter(v8::Local<v8::String> name, v8::Local<v8::Value> value, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.SVGPathSegArcAbs.r1._set");
    SVGPathSegArcAbs* imp = V8SVGPathSegArcAbs::toNative(info.Holder());
    float v = static_cast<float>(value->NumberValue());
    imp->setR1(v);
    if (SVGElement* context = V8Proxy::svgContext(imp))
        context->svgAttributeChanged(imp->associatedAttributeName());
    return;
}

static v8::Handle<v8::Value> r2AttrGetter(v8::Local<v8::String> name, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.SVGPathSegArcAbs.r2._get");
    SVGPathSegArcAbs* imp = V8SVGPathSegArcAbs::toNative(info.Holder());
    return v8::Number::New(imp->r2());
}

static void r2AttrSetter(v8::Local<v8::String> name, v8::Local<v8::Value> value, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.SVGPathSegArcAbs.r2._set");
    SVGPathSegArcAbs* imp = V8SVGPathSegArcAbs::toNative(info.Holder());
    float v = static_cast<float>(value->NumberValue());
    imp->setR2(v);
    if (SVGElement* context = V8Proxy::svgContext(imp))
        context->svgAttributeChanged(imp->associatedAttributeName());
    return;
}

static v8::Handle<v8::Value> angleAttrGetter(v8::Local<v8::String> name, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.SVGPathSegArcAbs.angle._get");
    SVGPathSegArcAbs* imp = V8SVGPathSegArcAbs::toNative(info.Holder());
    return v8::Number::New(imp->angle());
}

static void angleAttrSetter(v8::Local<v8::String> name, v8::Local<v8::Value> value, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.SVGPathSegArcAbs.angle._set");
    SVGPathSegArcAbs* imp = V8SVGPathSegArcAbs::toNative(info.Holder());
    float v = static_cast<float>(value->NumberValue());
    imp->setAngle(v);
    if (SVGElement* context = V8Proxy::svgContext(imp))
        context->svgAttributeChanged(imp->associatedAttributeName());
    return;
}

static v8::Handle<v8::Value> largeArcFlagAttrGetter(v8::Local<v8::String> name, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.SVGPathSegArcAbs.largeArcFlag._get");
    SVGPathSegArcAbs* imp = V8SVGPathSegArcAbs::toNative(info.Holder());
    return v8Boolean(imp->largeArcFlag());
}

static void largeArcFlagAttrSetter(v8::Local<v8::String> name, v8::Local<v8::Value> value, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.SVGPathSegArcAbs.largeArcFlag._set");
    SVGPathSegArcAbs* imp = V8SVGPathSegArcAbs::toNative(info.Holder());
    bool v = value->BooleanValue();
    imp->setLargeArcFlag(v);
    if (SVGElement* context = V8Proxy::svgContext(imp))
        context->svgAttributeChanged(imp->associatedAttributeName());
    return;
}

static v8::Handle<v8::Value> sweepFlagAttrGetter(v8::Local<v8::String> name, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.SVGPathSegArcAbs.sweepFlag._get");
    SVGPathSegArcAbs* imp = V8SVGPathSegArcAbs::toNative(info.Holder());
    return v8Boolean(imp->sweepFlag());
}

static void sweepFlagAttrSetter(v8::Local<v8::String> name, v8::Local<v8::Value> value, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.SVGPathSegArcAbs.sweepFlag._set");
    SVGPathSegArcAbs* imp = V8SVGPathSegArcAbs::toNative(info.Holder());
    bool v = value->BooleanValue();
    imp->setSweepFlag(v);
    if (SVGElement* context = V8Proxy::svgContext(imp))
        context->svgAttributeChanged(imp->associatedAttributeName());
    return;
}

} // namespace SVGPathSegArcAbsInternal

static const BatchedAttribute SVGPathSegArcAbsAttrs[] = {
    // Attribute 'x' (Type: 'attribute' ExtAttr: '')
    {"x", SVGPathSegArcAbsInternal::xAttrGetter, SVGPathSegArcAbsInternal::xAttrSetter, 0 /* no data */, static_cast<v8::AccessControl>(v8::DEFAULT), static_cast<v8::PropertyAttribute>(v8::None), 0 /* on instance */},
    // Attribute 'y' (Type: 'attribute' ExtAttr: '')
    {"y", SVGPathSegArcAbsInternal::yAttrGetter, SVGPathSegArcAbsInternal::yAttrSetter, 0 /* no data */, static_cast<v8::AccessControl>(v8::DEFAULT), static_cast<v8::PropertyAttribute>(v8::None), 0 /* on instance */},
    // Attribute 'r1' (Type: 'attribute' ExtAttr: '')
    {"r1", SVGPathSegArcAbsInternal::r1AttrGetter, SVGPathSegArcAbsInternal::r1AttrSetter, 0 /* no data */, static_cast<v8::AccessControl>(v8::DEFAULT), static_cast<v8::PropertyAttribute>(v8::None), 0 /* on instance */},
    // Attribute 'r2' (Type: 'attribute' ExtAttr: '')
    {"r2", SVGPathSegArcAbsInternal::r2AttrGetter, SVGPathSegArcAbsInternal::r2AttrSetter, 0 /* no data */, static_cast<v8::AccessControl>(v8::DEFAULT), static_cast<v8::PropertyAttribute>(v8::None), 0 /* on instance */},
    // Attribute 'angle' (Type: 'attribute' ExtAttr: '')
    {"angle", SVGPathSegArcAbsInternal::angleAttrGetter, SVGPathSegArcAbsInternal::angleAttrSetter, 0 /* no data */, static_cast<v8::AccessControl>(v8::DEFAULT), static_cast<v8::PropertyAttribute>(v8::None), 0 /* on instance */},
    // Attribute 'largeArcFlag' (Type: 'attribute' ExtAttr: '')
    {"largeArcFlag", SVGPathSegArcAbsInternal::largeArcFlagAttrGetter, SVGPathSegArcAbsInternal::largeArcFlagAttrSetter, 0 /* no data */, static_cast<v8::AccessControl>(v8::DEFAULT), static_cast<v8::PropertyAttribute>(v8::None), 0 /* on instance */},
    // Attribute 'sweepFlag' (Type: 'attribute' ExtAttr: '')
    {"sweepFlag", SVGPathSegArcAbsInternal::sweepFlagAttrGetter, SVGPathSegArcAbsInternal::sweepFlagAttrSetter, 0 /* no data */, static_cast<v8::AccessControl>(v8::DEFAULT), static_cast<v8::PropertyAttribute>(v8::None), 0 /* on instance */},
};
static v8::Persistent<v8::FunctionTemplate> ConfigureV8SVGPathSegArcAbsTemplate(v8::Persistent<v8::FunctionTemplate> desc)
{
    v8::Local<v8::Signature> defaultSignature = configureTemplate(desc, "SVGPathSegArcAbs", V8SVGPathSeg::GetTemplate(), V8SVGPathSegArcAbs::internalFieldCount,
        SVGPathSegArcAbsAttrs, sizeof(SVGPathSegArcAbsAttrs) / sizeof(*SVGPathSegArcAbsAttrs),
        0, 0);
    

    // Custom toString template
    desc->Set(getToStringName(), getToStringTemplate());
    return desc;
}

v8::Persistent<v8::FunctionTemplate> V8SVGPathSegArcAbs::GetRawTemplate()
{
    static v8::Persistent<v8::FunctionTemplate> V8SVGPathSegArcAbsRawCache = createRawTemplate();
    return V8SVGPathSegArcAbsRawCache;
}

v8::Persistent<v8::FunctionTemplate> V8SVGPathSegArcAbs::GetTemplate()
{
    static v8::Persistent<v8::FunctionTemplate> V8SVGPathSegArcAbsCache = ConfigureV8SVGPathSegArcAbsTemplate(GetRawTemplate());
    return V8SVGPathSegArcAbsCache;
}

SVGPathSegArcAbs* V8SVGPathSegArcAbs::toNative(v8::Handle<v8::Object> object)
{
    return reinterpret_cast<SVGPathSegArcAbs*>(object->GetPointerFromInternalField(v8DOMWrapperObjectIndex));
}

bool V8SVGPathSegArcAbs::HasInstance(v8::Handle<v8::Value> value)
{
    return GetRawTemplate()->HasInstance(value);
}


v8::Handle<v8::Object> V8SVGPathSegArcAbs::wrap(SVGPathSegArcAbs* impl)
{
    v8::Handle<v8::Object> wrapper;
    V8Proxy* proxy = 0;
        wrapper = getDOMSVGObjectWithContextMap().get(impl);
        if (!wrapper.IsEmpty())
            return wrapper;
    wrapper = V8DOMWrapper::instantiateV8Object(proxy, &info, impl);
    if (wrapper.IsEmpty())
        return wrapper;

    impl->ref();
    getDOMSVGObjectWithContextMap().set(impl, v8::Persistent<v8::Object>::New(wrapper));
    return wrapper;
}

v8::Handle<v8::Value> toV8(PassRefPtr<SVGPathSegArcAbs > impl)
{
    return toV8(impl.get());
}

v8::Handle<v8::Value> toV8(SVGPathSegArcAbs* impl)
{
    if (!impl)
        return v8::Null();
    return V8SVGPathSegArcAbs::wrap(impl);
}

void V8SVGPathSegArcAbs::derefObject(void* object)
{
    static_cast<SVGPathSegArcAbs*>(object)->deref();
}

} // namespace WebCore

#endif // ENABLE(SVG)
