/*
    This file is part of the WebKit open source project.
    This file has been generated by generate-bindings.pl. DO NOT MODIFY!

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Library General Public
    License as published by the Free Software Foundation; either
    version 2 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Library General Public License for more details.

    You should have received a copy of the GNU Library General Public License
    along with this library; see the file COPYING.LIB.  If not, write to
    the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
    Boston, MA 02111-1307, USA.
*/

#include "config.h"
#include "V8SVGPoint.h"

#if ENABLE(SVG)

#include "ExceptionCode.h"
#include "RuntimeEnabledFeatures.h"
#include "V8Binding.h"
#include "V8BindingState.h"
#include "V8DOMWrapper.h"
#include "V8IsolatedContext.h"
#include "V8Proxy.h"
#include "V8SVGMatrix.h"
#include "V8SVGPODTypeWrapper.h"

namespace WebCore {

WrapperTypeInfo V8SVGPoint::info = { V8SVGPoint::GetTemplate, V8SVGPoint::derefObject, 0 };

namespace SVGPointInternal {

template <typename T> void V8_USE(T) { }

static v8::Handle<v8::Value> xAttrGetter(v8::Local<v8::String> name, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.FloatPoint.x._get");
    V8SVGPODTypeWrapper<FloatPoint>* impWrapper = V8SVGPODTypeWrapper<FloatPoint>::toNative(info.Holder());
    FloatPoint impInstance = *impWrapper;
    FloatPoint* imp = &impInstance;
    return v8::Number::New(imp->x());
}

static void xAttrSetter(v8::Local<v8::String> name, v8::Local<v8::Value> value, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.SVGPoint.x._set");
    V8SVGPODTypeWrapper<FloatPoint>* wrapper = V8SVGPODTypeWrapper<FloatPoint>::toNative(info.Holder());
    FloatPoint impInstance = *wrapper;
    FloatPoint* imp = &impInstance;
    float v = static_cast<float>(value->NumberValue());
    imp->setX(v);
    wrapper->commitChange(*imp, V8Proxy::svgContext(wrapper));
    return;
}

static v8::Handle<v8::Value> yAttrGetter(v8::Local<v8::String> name, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.FloatPoint.y._get");
    V8SVGPODTypeWrapper<FloatPoint>* impWrapper = V8SVGPODTypeWrapper<FloatPoint>::toNative(info.Holder());
    FloatPoint impInstance = *impWrapper;
    FloatPoint* imp = &impInstance;
    return v8::Number::New(imp->y());
}

static void yAttrSetter(v8::Local<v8::String> name, v8::Local<v8::Value> value, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.SVGPoint.y._set");
    V8SVGPODTypeWrapper<FloatPoint>* wrapper = V8SVGPODTypeWrapper<FloatPoint>::toNative(info.Holder());
    FloatPoint impInstance = *wrapper;
    FloatPoint* imp = &impInstance;
    float v = static_cast<float>(value->NumberValue());
    imp->setY(v);
    wrapper->commitChange(*imp, V8Proxy::svgContext(wrapper));
    return;
}

static v8::Handle<v8::Value> matrixTransformCallback(const v8::Arguments& args)
{
    INC_STATS("DOM.SVGPoint.matrixTransform");
    V8SVGPODTypeWrapper<FloatPoint>* impWrapper = V8SVGPODTypeWrapper<FloatPoint>::toNative(args.Holder());
    FloatPoint impInstance = *impWrapper;
    FloatPoint* imp = &impInstance;
    ExceptionCode ec = 0;
    {
    bool matrixOk;
    AffineTransform matrix = V8SVGPODTypeUtil::toSVGPODType<AffineTransform>(&V8SVGMatrix::info, args[0], matrixOk);
    if (UNLIKELY(!matrixOk)) {
        ec = TYPE_MISMATCH_ERR;
        goto fail;
    }
    FloatPoint result = imp->matrixTransform(matrix);
    RefPtr<V8SVGPODTypeWrapper<FloatPoint> > wrapper = V8SVGStaticPODTypeWrapper<FloatPoint>::create(result);
    SVGElement* context = V8Proxy::svgContext(impWrapper);
    V8Proxy::setSVGContext(wrapper.get(), context);
    impWrapper->commitChange(impInstance, context);
    return toV8(wrapper.release());
    }
    fail:
    V8Proxy::setDOMException(ec);
    return v8::Handle<v8::Value>();
}

} // namespace SVGPointInternal

static const BatchedAttribute SVGPointAttrs[] = {
    // Attribute 'x' (Type: 'attribute' ExtAttr: '')
    {"x", SVGPointInternal::xAttrGetter, SVGPointInternal::xAttrSetter, 0 /* no data */, static_cast<v8::AccessControl>(v8::DEFAULT), static_cast<v8::PropertyAttribute>(v8::None), 0 /* on instance */},
    // Attribute 'y' (Type: 'attribute' ExtAttr: '')
    {"y", SVGPointInternal::yAttrGetter, SVGPointInternal::yAttrSetter, 0 /* no data */, static_cast<v8::AccessControl>(v8::DEFAULT), static_cast<v8::PropertyAttribute>(v8::None), 0 /* on instance */},
};
static const BatchedCallback SVGPointCallbacks[] = {
    {"matrixTransform", SVGPointInternal::matrixTransformCallback},
};
static v8::Persistent<v8::FunctionTemplate> ConfigureV8SVGPointTemplate(v8::Persistent<v8::FunctionTemplate> desc)
{
    v8::Local<v8::Signature> defaultSignature = configureTemplate(desc, "SVGPoint", v8::Persistent<v8::FunctionTemplate>(), V8SVGPoint::internalFieldCount,
        SVGPointAttrs, sizeof(SVGPointAttrs) / sizeof(*SVGPointAttrs),
        SVGPointCallbacks, sizeof(SVGPointCallbacks) / sizeof(*SVGPointCallbacks));
    v8::Local<v8::ObjectTemplate> instance = desc->InstanceTemplate();
    v8::Local<v8::ObjectTemplate> proto = desc->PrototypeTemplate();
    

    // Custom toString template
    desc->Set(getToStringName(), getToStringTemplate());
    return desc;
}

v8::Persistent<v8::FunctionTemplate> V8SVGPoint::GetRawTemplate()
{
    static v8::Persistent<v8::FunctionTemplate> V8SVGPointRawCache = createRawTemplate();
    return V8SVGPointRawCache;
}

v8::Persistent<v8::FunctionTemplate> V8SVGPoint::GetTemplate()
{
    static v8::Persistent<v8::FunctionTemplate> V8SVGPointCache = ConfigureV8SVGPointTemplate(GetRawTemplate());
    return V8SVGPointCache;
}

V8SVGPODTypeWrapper<FloatPoint>* V8SVGPoint::toNative(v8::Handle<v8::Object> object)
{
    return reinterpret_cast<V8SVGPODTypeWrapper<FloatPoint>*>(object->GetPointerFromInternalField(v8DOMWrapperObjectIndex));
}

bool V8SVGPoint::HasInstance(v8::Handle<v8::Value> value)
{
    return GetRawTemplate()->HasInstance(value);
}


v8::Handle<v8::Object> V8SVGPoint::wrap(V8SVGPODTypeWrapper<FloatPoint>* impl)
{
    v8::Handle<v8::Object> wrapper;
    V8Proxy* proxy = 0;
        wrapper = getDOMSVGObjectWithContextMap().get(impl);
        if (!wrapper.IsEmpty())
            return wrapper;
    wrapper = V8DOMWrapper::instantiateV8Object(proxy, &info, impl);
    if (wrapper.IsEmpty())
        return wrapper;

    impl->ref();
    getDOMSVGObjectWithContextMap().set(impl, v8::Persistent<v8::Object>::New(wrapper));
    return wrapper;
}

v8::Handle<v8::Value> toV8(PassRefPtr<V8SVGPODTypeWrapper<FloatPoint> > impl)
{
    return toV8(impl.get());
}

v8::Handle<v8::Value> toV8(V8SVGPODTypeWrapper<FloatPoint>* impl)
{
    if (!impl)
        return v8::Null();
    return V8SVGPoint::wrap(impl);
}

void V8SVGPoint::derefObject(void* object)
{
    static_cast<V8SVGPODTypeWrapper<FloatPoint>*>(object)->deref();
}

} // namespace WebCore

#endif // ENABLE(SVG)
