/*
    This file is part of the WebKit open source project.
    This file has been generated by generate-bindings.pl. DO NOT MODIFY!

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Library General Public
    License as published by the Free Software Foundation; either
    version 2 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Library General Public License for more details.

    You should have received a copy of the GNU Library General Public License
    along with this library; see the file COPYING.LIB.  If not, write to
    the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
    Boston, MA 02111-1307, USA.
*/

#include "config.h"
#include "V8SVGMarkerElement.h"

#if ENABLE(SVG)

#include "CSSMutableStyleDeclaration.h"
#include "ExceptionCode.h"
#include "RuntimeEnabledFeatures.h"
#include "V8Binding.h"
#include "V8BindingMacros.h"
#include "V8BindingState.h"
#include "V8CSSStyleDeclaration.h"
#include "V8CSSValue.h"
#include "V8DOMWrapper.h"
#include "V8IsolatedContext.h"
#include "V8Proxy.h"
#include "V8SVGAngle.h"
#include "V8SVGAnimatedAngle.h"
#include "V8SVGAnimatedBoolean.h"
#include "V8SVGAnimatedEnumeration.h"
#include "V8SVGAnimatedLength.h"
#include "V8SVGAnimatedPreserveAspectRatio.h"
#include "V8SVGAnimatedRect.h"
#include "V8SVGAnimatedString.h"
#include "V8SVGElement.h"
#include "V8SVGPODTypeWrapper.h"
#include <wtf/GetPtr.h>
#include <wtf/RefCounted.h>
#include <wtf/RefPtr.h>

namespace WebCore {

WrapperTypeInfo V8SVGMarkerElement::info = { V8SVGMarkerElement::GetTemplate, V8SVGMarkerElement::derefObject, 0 };

namespace SVGMarkerElementInternal {

template <typename T> void V8_USE(T) { }

static v8::Handle<v8::Value> refXAttrGetter(v8::Local<v8::String> name, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.SVGMarkerElement.refX._get");
    SVGMarkerElement* imp = V8SVGMarkerElement::toNative(info.Holder());
    SVGElement* context = imp;
    PassRefPtr<SVGAnimatedLength> resultAsPassRefPtr = V8Proxy::withSVGContext(imp->refXAnimated(), context);
    return toV8(resultAsPassRefPtr);
}

static v8::Handle<v8::Value> refYAttrGetter(v8::Local<v8::String> name, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.SVGMarkerElement.refY._get");
    SVGMarkerElement* imp = V8SVGMarkerElement::toNative(info.Holder());
    SVGElement* context = imp;
    PassRefPtr<SVGAnimatedLength> resultAsPassRefPtr = V8Proxy::withSVGContext(imp->refYAnimated(), context);
    return toV8(resultAsPassRefPtr);
}

static v8::Handle<v8::Value> markerUnitsAttrGetter(v8::Local<v8::String> name, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.SVGMarkerElement.markerUnits._get");
    SVGMarkerElement* imp = V8SVGMarkerElement::toNative(info.Holder());
    SVGElement* context = imp;
    PassRefPtr<SVGAnimatedEnumeration> resultAsPassRefPtr = V8Proxy::withSVGContext(imp->markerUnitsAnimated(), context);
    return toV8(resultAsPassRefPtr);
}

static v8::Handle<v8::Value> markerWidthAttrGetter(v8::Local<v8::String> name, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.SVGMarkerElement.markerWidth._get");
    SVGMarkerElement* imp = V8SVGMarkerElement::toNative(info.Holder());
    SVGElement* context = imp;
    PassRefPtr<SVGAnimatedLength> resultAsPassRefPtr = V8Proxy::withSVGContext(imp->markerWidthAnimated(), context);
    return toV8(resultAsPassRefPtr);
}

static v8::Handle<v8::Value> markerHeightAttrGetter(v8::Local<v8::String> name, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.SVGMarkerElement.markerHeight._get");
    SVGMarkerElement* imp = V8SVGMarkerElement::toNative(info.Holder());
    SVGElement* context = imp;
    PassRefPtr<SVGAnimatedLength> resultAsPassRefPtr = V8Proxy::withSVGContext(imp->markerHeightAnimated(), context);
    return toV8(resultAsPassRefPtr);
}

static v8::Handle<v8::Value> orientTypeAttrGetter(v8::Local<v8::String> name, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.SVGMarkerElement.orientType._get");
    SVGMarkerElement* imp = V8SVGMarkerElement::toNative(info.Holder());
    SVGElement* context = imp;
    PassRefPtr<SVGAnimatedEnumeration> resultAsPassRefPtr = V8Proxy::withSVGContext(imp->orientTypeAnimated(), context);
    return toV8(resultAsPassRefPtr);
}

static v8::Handle<v8::Value> orientAngleAttrGetter(v8::Local<v8::String> name, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.SVGMarkerElement.orientAngle._get");
    SVGMarkerElement* imp = V8SVGMarkerElement::toNative(info.Holder());
    SVGElement* context = imp;
    PassRefPtr<SVGAnimatedAngle> resultAsPassRefPtr = V8Proxy::withSVGContext(imp->orientAngleAnimated(), context);
    return toV8(resultAsPassRefPtr);
}

static v8::Handle<v8::Value> xmllangAttrGetter(v8::Local<v8::String> name, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.SVGMarkerElement.xmllang._get");
    SVGMarkerElement* imp = V8SVGMarkerElement::toNative(info.Holder());
    return v8String(imp->xmllang());
}

static void xmllangAttrSetter(v8::Local<v8::String> name, v8::Local<v8::Value> value, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.SVGMarkerElement.xmllang._set");
    SVGMarkerElement* imp = V8SVGMarkerElement::toNative(info.Holder());
    V8Parameter<> v = value;
    imp->setXmllang(v);
    return;
}

static v8::Handle<v8::Value> xmlspaceAttrGetter(v8::Local<v8::String> name, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.SVGMarkerElement.xmlspace._get");
    SVGMarkerElement* imp = V8SVGMarkerElement::toNative(info.Holder());
    return v8String(imp->xmlspace());
}

static void xmlspaceAttrSetter(v8::Local<v8::String> name, v8::Local<v8::Value> value, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.SVGMarkerElement.xmlspace._set");
    SVGMarkerElement* imp = V8SVGMarkerElement::toNative(info.Holder());
    V8Parameter<> v = value;
    imp->setXmlspace(v);
    return;
}

static v8::Handle<v8::Value> externalResourcesRequiredAttrGetter(v8::Local<v8::String> name, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.SVGMarkerElement.externalResourcesRequired._get");
    SVGMarkerElement* imp = V8SVGMarkerElement::toNative(info.Holder());
    SVGElement* context = imp;
    PassRefPtr<SVGAnimatedBoolean> resultAsPassRefPtr = V8Proxy::withSVGContext(imp->externalResourcesRequiredAnimated(), context);
    return toV8(resultAsPassRefPtr);
}

static v8::Handle<v8::Value> classNameAttrGetter(v8::Local<v8::String> name, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.SVGMarkerElement.className._get");
    SVGMarkerElement* imp = V8SVGMarkerElement::toNative(info.Holder());
    SVGElement* context = imp;
    PassRefPtr<SVGAnimatedString> resultAsPassRefPtr = V8Proxy::withSVGContext(imp->classNameAnimated(), context);
    return toV8(resultAsPassRefPtr);
}

static v8::Handle<v8::Value> styleAttrGetter(v8::Local<v8::String> name, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.SVGMarkerElement.style._get");
    SVGMarkerElement* imp = V8SVGMarkerElement::toNative(info.Holder());
    return toV8(imp->style());
}

static v8::Handle<v8::Value> viewBoxAttrGetter(v8::Local<v8::String> name, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.SVGMarkerElement.viewBox._get");
    SVGMarkerElement* imp = V8SVGMarkerElement::toNative(info.Holder());
    SVGElement* context = imp;
    PassRefPtr<SVGAnimatedRect> resultAsPassRefPtr = V8Proxy::withSVGContext(imp->viewBoxAnimated(), context);
    return toV8(resultAsPassRefPtr);
}

static v8::Handle<v8::Value> preserveAspectRatioAttrGetter(v8::Local<v8::String> name, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.SVGMarkerElement.preserveAspectRatio._get");
    SVGMarkerElement* imp = V8SVGMarkerElement::toNative(info.Holder());
    SVGElement* context = imp;
    PassRefPtr<SVGAnimatedPreserveAspectRatio> resultAsPassRefPtr = V8Proxy::withSVGContext(imp->preserveAspectRatioAnimated(), context);
    return toV8(resultAsPassRefPtr);
}

static v8::Handle<v8::Value> setOrientToAutoCallback(const v8::Arguments& args)
{
    INC_STATS("DOM.SVGMarkerElement.setOrientToAuto");
    SVGMarkerElement* imp = V8SVGMarkerElement::toNative(args.Holder());
    imp->setOrientToAuto();
    return v8::Handle<v8::Value>();
}

static v8::Handle<v8::Value> setOrientToAngleCallback(const v8::Arguments& args)
{
    INC_STATS("DOM.SVGMarkerElement.setOrientToAngle");
    SVGMarkerElement* imp = V8SVGMarkerElement::toNative(args.Holder());
    ExceptionCode ec = 0;
    {
    bool angleOk;
    SVGAngle angle = V8SVGPODTypeUtil::toSVGPODType<SVGAngle>(&V8SVGAngle::info, args[0], angleOk);
    if (UNLIKELY(!angleOk)) {
        ec = TYPE_MISMATCH_ERR;
        goto fail;
    }
    imp->setOrientToAngle(angle);
    return v8::Handle<v8::Value>();
    }
    fail:
    V8Proxy::setDOMException(ec);
    return v8::Handle<v8::Value>();
}

static v8::Handle<v8::Value> getPresentationAttributeCallback(const v8::Arguments& args)
{
    INC_STATS("DOM.SVGMarkerElement.getPresentationAttribute");
    SVGMarkerElement* imp = V8SVGMarkerElement::toNative(args.Holder());
    STRING_TO_V8PARAMETER_EXCEPTION_BLOCK(V8Parameter<>, name, args[0]);
    return toV8(imp->getPresentationAttribute(name));
}

} // namespace SVGMarkerElementInternal

static const BatchedAttribute SVGMarkerElementAttrs[] = {
    // Attribute 'refX' (Type: 'readonly attribute' ExtAttr: '')
    {"refX", SVGMarkerElementInternal::refXAttrGetter, 0, 0 /* no data */, static_cast<v8::AccessControl>(v8::DEFAULT), static_cast<v8::PropertyAttribute>(v8::None), 0 /* on instance */},
    // Attribute 'refY' (Type: 'readonly attribute' ExtAttr: '')
    {"refY", SVGMarkerElementInternal::refYAttrGetter, 0, 0 /* no data */, static_cast<v8::AccessControl>(v8::DEFAULT), static_cast<v8::PropertyAttribute>(v8::None), 0 /* on instance */},
    // Attribute 'markerUnits' (Type: 'readonly attribute' ExtAttr: '')
    {"markerUnits", SVGMarkerElementInternal::markerUnitsAttrGetter, 0, 0 /* no data */, static_cast<v8::AccessControl>(v8::DEFAULT), static_cast<v8::PropertyAttribute>(v8::None), 0 /* on instance */},
    // Attribute 'markerWidth' (Type: 'readonly attribute' ExtAttr: '')
    {"markerWidth", SVGMarkerElementInternal::markerWidthAttrGetter, 0, 0 /* no data */, static_cast<v8::AccessControl>(v8::DEFAULT), static_cast<v8::PropertyAttribute>(v8::None), 0 /* on instance */},
    // Attribute 'markerHeight' (Type: 'readonly attribute' ExtAttr: '')
    {"markerHeight", SVGMarkerElementInternal::markerHeightAttrGetter, 0, 0 /* no data */, static_cast<v8::AccessControl>(v8::DEFAULT), static_cast<v8::PropertyAttribute>(v8::None), 0 /* on instance */},
    // Attribute 'orientType' (Type: 'readonly attribute' ExtAttr: '')
    {"orientType", SVGMarkerElementInternal::orientTypeAttrGetter, 0, 0 /* no data */, static_cast<v8::AccessControl>(v8::DEFAULT), static_cast<v8::PropertyAttribute>(v8::None), 0 /* on instance */},
    // Attribute 'orientAngle' (Type: 'readonly attribute' ExtAttr: '')
    {"orientAngle", SVGMarkerElementInternal::orientAngleAttrGetter, 0, 0 /* no data */, static_cast<v8::AccessControl>(v8::DEFAULT), static_cast<v8::PropertyAttribute>(v8::None), 0 /* on instance */},
    // Attribute 'xmllang' (Type: 'attribute' ExtAttr: '')
    {"xmllang", SVGMarkerElementInternal::xmllangAttrGetter, SVGMarkerElementInternal::xmllangAttrSetter, 0 /* no data */, static_cast<v8::AccessControl>(v8::DEFAULT), static_cast<v8::PropertyAttribute>(v8::None), 0 /* on instance */},
    // Attribute 'xmlspace' (Type: 'attribute' ExtAttr: '')
    {"xmlspace", SVGMarkerElementInternal::xmlspaceAttrGetter, SVGMarkerElementInternal::xmlspaceAttrSetter, 0 /* no data */, static_cast<v8::AccessControl>(v8::DEFAULT), static_cast<v8::PropertyAttribute>(v8::None), 0 /* on instance */},
    // Attribute 'externalResourcesRequired' (Type: 'readonly attribute' ExtAttr: '')
    {"externalResourcesRequired", SVGMarkerElementInternal::externalResourcesRequiredAttrGetter, 0, 0 /* no data */, static_cast<v8::AccessControl>(v8::DEFAULT), static_cast<v8::PropertyAttribute>(v8::None), 0 /* on instance */},
    // Attribute 'className' (Type: 'readonly attribute' ExtAttr: '')
    {"className", SVGMarkerElementInternal::classNameAttrGetter, 0, 0 /* no data */, static_cast<v8::AccessControl>(v8::DEFAULT), static_cast<v8::PropertyAttribute>(v8::None), 0 /* on instance */},
    // Attribute 'style' (Type: 'readonly attribute' ExtAttr: '')
    {"style", SVGMarkerElementInternal::styleAttrGetter, 0, 0 /* no data */, static_cast<v8::AccessControl>(v8::DEFAULT), static_cast<v8::PropertyAttribute>(v8::None), 0 /* on instance */},
    // Attribute 'viewBox' (Type: 'readonly attribute' ExtAttr: '')
    {"viewBox", SVGMarkerElementInternal::viewBoxAttrGetter, 0, 0 /* no data */, static_cast<v8::AccessControl>(v8::DEFAULT), static_cast<v8::PropertyAttribute>(v8::None), 0 /* on instance */},
    // Attribute 'preserveAspectRatio' (Type: 'readonly attribute' ExtAttr: '')
    {"preserveAspectRatio", SVGMarkerElementInternal::preserveAspectRatioAttrGetter, 0, 0 /* no data */, static_cast<v8::AccessControl>(v8::DEFAULT), static_cast<v8::PropertyAttribute>(v8::None), 0 /* on instance */},
};
static const BatchedCallback SVGMarkerElementCallbacks[] = {
    {"setOrientToAuto", SVGMarkerElementInternal::setOrientToAutoCallback},
    {"setOrientToAngle", SVGMarkerElementInternal::setOrientToAngleCallback},
    {"getPresentationAttribute", SVGMarkerElementInternal::getPresentationAttributeCallback},
};
static const BatchedConstant SVGMarkerElementConsts[] = {
    {"SVG_MARKERUNITS_UNKNOWN", static_cast<signed int>(0)},
    {"SVG_MARKERUNITS_USERSPACEONUSE", static_cast<signed int>(1)},
    {"SVG_MARKERUNITS_STROKEWIDTH", static_cast<signed int>(2)},
    {"SVG_MARKER_ORIENT_UNKNOWN", static_cast<signed int>(0)},
    {"SVG_MARKER_ORIENT_AUTO", static_cast<signed int>(1)},
    {"SVG_MARKER_ORIENT_ANGLE", static_cast<signed int>(2)},
};

COMPILE_ASSERT(0 == SVGMarkerElement::SVG_MARKERUNITS_UNKNOWN, SVGMarkerElementEnumSVG_MARKERUNITS_UNKNOWNIsWrongUseDontCheckEnums);
COMPILE_ASSERT(1 == SVGMarkerElement::SVG_MARKERUNITS_USERSPACEONUSE, SVGMarkerElementEnumSVG_MARKERUNITS_USERSPACEONUSEIsWrongUseDontCheckEnums);
COMPILE_ASSERT(2 == SVGMarkerElement::SVG_MARKERUNITS_STROKEWIDTH, SVGMarkerElementEnumSVG_MARKERUNITS_STROKEWIDTHIsWrongUseDontCheckEnums);
COMPILE_ASSERT(0 == SVGMarkerElement::SVG_MARKER_ORIENT_UNKNOWN, SVGMarkerElementEnumSVG_MARKER_ORIENT_UNKNOWNIsWrongUseDontCheckEnums);
COMPILE_ASSERT(1 == SVGMarkerElement::SVG_MARKER_ORIENT_AUTO, SVGMarkerElementEnumSVG_MARKER_ORIENT_AUTOIsWrongUseDontCheckEnums);
COMPILE_ASSERT(2 == SVGMarkerElement::SVG_MARKER_ORIENT_ANGLE, SVGMarkerElementEnumSVG_MARKER_ORIENT_ANGLEIsWrongUseDontCheckEnums);

static v8::Persistent<v8::FunctionTemplate> ConfigureV8SVGMarkerElementTemplate(v8::Persistent<v8::FunctionTemplate> desc)
{
    v8::Local<v8::Signature> defaultSignature = configureTemplate(desc, "SVGMarkerElement", V8SVGElement::GetTemplate(), V8SVGMarkerElement::internalFieldCount,
        SVGMarkerElementAttrs, sizeof(SVGMarkerElementAttrs) / sizeof(*SVGMarkerElementAttrs),
        SVGMarkerElementCallbacks, sizeof(SVGMarkerElementCallbacks) / sizeof(*SVGMarkerElementCallbacks));
    v8::Local<v8::ObjectTemplate> instance = desc->InstanceTemplate();
    v8::Local<v8::ObjectTemplate> proto = desc->PrototypeTemplate();
    
    batchConfigureConstants(desc, proto, SVGMarkerElementConsts, sizeof(SVGMarkerElementConsts) / sizeof(*SVGMarkerElementConsts));

    // Custom toString template
    desc->Set(getToStringName(), getToStringTemplate());
    return desc;
}

v8::Persistent<v8::FunctionTemplate> V8SVGMarkerElement::GetRawTemplate()
{
    static v8::Persistent<v8::FunctionTemplate> V8SVGMarkerElementRawCache = createRawTemplate();
    return V8SVGMarkerElementRawCache;
}

v8::Persistent<v8::FunctionTemplate> V8SVGMarkerElement::GetTemplate()
{
    static v8::Persistent<v8::FunctionTemplate> V8SVGMarkerElementCache = ConfigureV8SVGMarkerElementTemplate(GetRawTemplate());
    return V8SVGMarkerElementCache;
}

SVGMarkerElement* V8SVGMarkerElement::toNative(v8::Handle<v8::Object> object)
{
    return reinterpret_cast<SVGMarkerElement*>(object->GetPointerFromInternalField(v8DOMWrapperObjectIndex));
}

bool V8SVGMarkerElement::HasInstance(v8::Handle<v8::Value> value)
{
    return GetRawTemplate()->HasInstance(value);
}


v8::Handle<v8::Object> V8SVGMarkerElement::wrap(SVGMarkerElement* impl)
{
    v8::Handle<v8::Object> wrapper;
    V8Proxy* proxy = 0;
    if (impl->document()) {
        proxy = V8Proxy::retrieve(impl->document()->frame());
        if (proxy && static_cast<Node*>(impl->document()) == static_cast<Node*>(impl))
            proxy->windowShell()->initContextIfNeeded();
    }

        wrapper = V8DOMWrapper::getWrapper(impl);
        if (!wrapper.IsEmpty())
            return wrapper;

    v8::Handle<v8::Context> context;
    if (proxy)
        context = proxy->context();

    // Enter the node's context and create the wrapper in that context.
    if (!context.IsEmpty())
        context->Enter();
    wrapper = V8DOMWrapper::instantiateV8Object(proxy, &info, impl);
    // Exit the node's context if it was entered.
    if (!context.IsEmpty())
        context->Exit();
    if (wrapper.IsEmpty())
        return wrapper;

    impl->ref();
    getDOMNodeMap().set(impl, v8::Persistent<v8::Object>::New(wrapper));
    return wrapper;
}

v8::Handle<v8::Value> toV8(PassRefPtr<SVGMarkerElement > impl)
{
    return toV8(impl.get());
}

v8::Handle<v8::Value> toV8(SVGMarkerElement* impl)
{
    if (!impl)
        return v8::Null();
    return V8SVGMarkerElement::wrap(impl);
}

void V8SVGMarkerElement::derefObject(void* object)
{
    static_cast<SVGMarkerElement*>(object)->deref();
}

} // namespace WebCore

#endif // ENABLE(SVG)
