/*
    This file is part of the WebKit open source project.
    This file has been generated by generate-bindings.pl. DO NOT MODIFY!

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Library General Public
    License as published by the Free Software Foundation; either
    version 2 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Library General Public License for more details.

    You should have received a copy of the GNU Library General Public License
    along with this library; see the file COPYING.LIB.  If not, write to
    the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
    Boston, MA 02111-1307, USA.
*/

#include "config.h"
#include "V8TextMetrics.h"

#include "RuntimeEnabledFeatures.h"
#include "V8Binding.h"
#include "V8BindingState.h"
#include "V8DOMWrapper.h"
#include "V8IsolatedContext.h"
#include "V8Proxy.h"

namespace WebCore {

WrapperTypeInfo V8TextMetrics::info = { V8TextMetrics::GetTemplate, V8TextMetrics::derefObject, 0 };

namespace TextMetricsInternal {

template <typename T> void V8_USE(T) { }

static v8::Handle<v8::Value> widthAttrGetter(v8::Local<v8::String> name, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.TextMetrics.width._get");
    TextMetrics* imp = V8TextMetrics::toNative(info.Holder());
    return v8::Number::New(imp->width());
}

} // namespace TextMetricsInternal

static const BatchedAttribute TextMetricsAttrs[] = {
    // Attribute 'width' (Type: 'readonly attribute' ExtAttr: '')
    {"width", TextMetricsInternal::widthAttrGetter, 0, 0 /* no data */, static_cast<v8::AccessControl>(v8::DEFAULT), static_cast<v8::PropertyAttribute>(v8::None), 0 /* on instance */},
};
static v8::Persistent<v8::FunctionTemplate> ConfigureV8TextMetricsTemplate(v8::Persistent<v8::FunctionTemplate> desc)
{
    v8::Local<v8::Signature> defaultSignature = configureTemplate(desc, "TextMetrics", v8::Persistent<v8::FunctionTemplate>(), V8TextMetrics::internalFieldCount,
        TextMetricsAttrs, sizeof(TextMetricsAttrs) / sizeof(*TextMetricsAttrs),
        0, 0);
    

    // Custom toString template
    desc->Set(getToStringName(), getToStringTemplate());
    return desc;
}

v8::Persistent<v8::FunctionTemplate> V8TextMetrics::GetRawTemplate()
{
    static v8::Persistent<v8::FunctionTemplate> V8TextMetricsRawCache = createRawTemplate();
    return V8TextMetricsRawCache;
}

v8::Persistent<v8::FunctionTemplate> V8TextMetrics::GetTemplate()
{
    static v8::Persistent<v8::FunctionTemplate> V8TextMetricsCache = ConfigureV8TextMetricsTemplate(GetRawTemplate());
    return V8TextMetricsCache;
}

TextMetrics* V8TextMetrics::toNative(v8::Handle<v8::Object> object)
{
    return reinterpret_cast<TextMetrics*>(object->GetPointerFromInternalField(v8DOMWrapperObjectIndex));
}

bool V8TextMetrics::HasInstance(v8::Handle<v8::Value> value)
{
    return GetRawTemplate()->HasInstance(value);
}


v8::Handle<v8::Object> V8TextMetrics::wrap(TextMetrics* impl)
{
    v8::Handle<v8::Object> wrapper;
    V8Proxy* proxy = 0;
        wrapper = getDOMObjectMap().get(impl);
        if (!wrapper.IsEmpty())
            return wrapper;
    wrapper = V8DOMWrapper::instantiateV8Object(proxy, &info, impl);
    if (wrapper.IsEmpty())
        return wrapper;

    impl->ref();
    getDOMObjectMap().set(impl, v8::Persistent<v8::Object>::New(wrapper));
    return wrapper;
}

v8::Handle<v8::Value> toV8(PassRefPtr<TextMetrics > impl)
{
    return toV8(impl.get());
}

v8::Handle<v8::Value> toV8(TextMetrics* impl)
{
    if (!impl)
        return v8::Null();
    return V8TextMetrics::wrap(impl);
}

void V8TextMetrics::derefObject(void* object)
{
    static_cast<TextMetrics*>(object)->deref();
}

} // namespace WebCore
